### ISSUE TITLE
Try to write code with fewer branches?

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#103]
The more I read about processor architecture the more I realize that branch prediction is fickle and the penalty for a failed prediction is high (10-20 clock cycles). Even when branch prediction is effective, having too many branches close together can slow things down (I read something about branch prediction being slower on some i7 version if there is more than 1 branch per 16 bytes of instructions).

So perhaps it would behoove us to use idioms that combine multiple (easily-tested) conditions in one word before branching. Something like
```
if (x | y) {
    ...
}
```
(where it works, say) might actually be faster than
```
if (x || y) {
    ...
}
```
Then again, maybe the compiler (optimizer) also knows this and will do it for us?

**Comment by gvanrossum** [comment]
> Wouldn't that miss out on short-circuiting?

Indeed, that's the whole point -- *if* you have a condition where short-circuiting is not essential, you may be better off combining two flags using e.g. `x | y` since modern pipelining CPUs can do that much faster than `x && y`.

Of course this isn't an option if condition `x` is a check that a pointer isn't NULL and `y` dereferences that pointer. But there are some cases where we just check for independent flags, and what I've learned seems to indicate that one branch is easier than two (if the branches are very close together in the machine code).

**Comment by Fidget-Spinner** [comment]
Some clarification:

Clang [outright ignores likely/unlikely during PGO](https://clang.llvm.org/docs/AttributeReference.html#likely-and-unlikely) as it already collects branch weights.

GCC [seems to combine the weights with PGO data](https://gcc.gnu.org/legacy-ml/gcc-help/2011-12/msg00193.html). (No clue if that information is still up to date).

It seems that good PGO training is ever more important, linking back to #99.

**Comment by erlend-aasland** [comment]
`LIKELY`/`UNLIKELY` could still be interesting for debug builds (FWIW) and other build configurations (for example `-Os` and `-Oz` both run without PGO, AFAIK).
