### ISSUE TITLE
List comprehensions could pre-allocate the list.

### ISSUE THREAD

**Issue by sweeneyde** [faster-cpython/ideas#113]
List comprehensions/LIST_APPEND could probably be streamlined so as not to do so many reallocs in some cases.

Current code for `[x+1 for x in it]`:
```
 1           0 BUILD_LIST               ​0
             ​2 LOAD_FAST                0 (.0)
       ​>>    4 FOR_ITER                 6 (to 18)
             ​6 STORE_FAST               1 (x)
             ​8 LOAD_FAST                1 (x)
            ​10 LOAD_CONST               0 (1)
            ​12 BINARY_ADD
            ​14 LIST_APPEND              2
            ​16 JUMP_ABSOLUTE            2 (to 4)
       ​>>   18 RETURN_VALUE
```

I propose something like this:
```
LOAD_FAST .0
LIST_ALLOC_LENGTH_HINT .0
    * Push a list with length_hint(TOS) allocated
ROT_TWO
FOR_ITER
STORE_FAST
LOAD_FAST
LOAD_CONST
BINARY_ADD
LIST_APPEND_FAST
    * Don't call list_resize: don't shrink the list if over-allocated.
    * Just check that allocated > size, then size++ and SET_ITEM.
        * If no room, only then call list_resize. 
    * Consume the references to eliminate an INCREF/DECREF pair
JUMP_ABSOLUTE
TRIM_LIST
    * list_resize(list, Py_SIZE(list))
    * Just in case length_hint was wildly incorrect; usually don't malloc.
RETURN_VALUE
```

LIST_APPEND also gets used elsewhere (e.g., when BUILD_LIST overflows), so I don't know the best way to make that usage harmonize with these changes. Maybe just force that use-case to use EXTENDED_ARG instead?

**Comment by josalhor** [comment]
On another note, I find it surprising that the C API doesn't have a PyList_Reserve(PyObject *p, Py_ssize_t len) that reserves enough space to set items directly with SET_ITEM (on the public API at least). I remember reading some discussion about this, but I can't find the related issue.

**Comment by erlend-aasland** [comment]
> On another note, I find it surprising that the C API doesn't have a PyList_Reserve(PyObject *p, Py_ssize_t len) that reserves enough space to set items directly with SET_ITEM [...]

Use [PyList_New](https://docs.python.org/3/c-api/list.html#c.PyList_New) with a length greater than zero. Use [PyList_SET_ITEM](https://docs.python.org/3/c-api/list.html#c.PyList_SET_ITEM) to fill it.

```c
const int sz = 10;
PyObject *list = PyList(sz);
if (list == NULL) {
    /* error handling */
}
for (int i = 0; i < sz; i++) {
    PyList_SET_ITEM(list, ...);
}
```

https://github.com/python/cpython/blob/fc9b62281931da8d20f85d5ed44cfc24f068d3f4/Objects/listobject.c#L140-L182

**Comment by josalhor** [comment]
> Use PyList_New with a length greater than zero. Use PyList_SET_ITEM to fill it.

But that requires creating a new object, which is not the intended effect. I meant something closer to [C++ reserve](https://www.cplusplus.com/reference/vector/vector/reserve/). It should be roughly equivalent to [list_resize](https://github.com/python/cpython/blob/main/Objects/listobject.c#L41).

**Comment by erlend-aasland** [comment]
Perhaps something like `_PyTuple_FromArray` (but for lists instead of tuples)?

**Comment by gvanrossum** [comment]
If you find it surprising that such an API doesn’t exist, can you give some important (real world) use cases for it?

**Comment by methane** [comment]
Tuple has only size. But List has size and capacity.
This proposal is creating new list with size=0 and capacity=N.

**Comment by isidentical** [comment]
Also see: [Optimize list comprehensions with preallocate size and protect against overflow](https://bugs.python.org/issue36551)

**Comment by sweeneyde** [comment]
Thanks, somehow my search missed that issue. Since it looks like this has been tried already, I'm not going to spend effort trying again at this point.

**Comment by methane** [comment]
The issue had been rejected because `__length_hint__` is not so useful.

PEP 424 says:

> This method is then used by various other functions (such as list) to presize lists based on the estimate returned by `__length_hint__`.

I think PEP 424 is mistake. `__length_hit__` can not be used to presize lists in many cases.

I think `PyObject_Size()` without TypeError would be better. It works for tuple, list, dict, and range.
