### ISSUE TITLE
Specialize COMPARE_OP

### ISSUE THREAD

**Issue by sweeneyde** [faster-cpython/ideas#116]
Some specialization statistics:

https://gist.github.com/sweeneyde/49cc3a9d074d56cf095cb0a42d13d7a4

Including 3 opcodes: COMPARE_OP_INT and COMPARE_OP_FLOAT and COMPARE_OP_STR (equality only) seems to give pretty good specialization numbers.

**Comment by sweeneyde** [comment]
I opened https://github.com/python/cpython/pull/29734

**Comment by gvanrossum** [comment]
(To be clear, that PR was merged. Thanks, Dennis!)
