### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#12]
Ideally our optimization work will be guided by profiling data.  There are a number of factors to sort out in this area:

* results already posted by other parties
* tooling
* targets (e.g. C-level eval loop code vs. opcode hits vs. ???)
* workloads

**Comment by gvanrossum** [comment]
Curious whether [Austin](https://github.com/P403n1x87/austin) might be useful here. It's billed as a sampling profiler for Python programs, but it's pure C code.

**Comment by ericsnowcurrently** [comment]
Also, @gramster mentioned [bprof](https://bprof.github.io/bprof/) to me and indicated that @jakebailey may have some good insight on it.

**Comment by jakebailey** [comment]
May have misheard; I use https://github.com/google/pprof (mainly for Go and Node), which does have a C/C++ library I haven't tried out (but is used for profiling chromium, for example).

**Comment by ericsnowcurrently** [comment]
Ah, I definitely misheard. 😄

**Comment by sweeneyde** [comment]
The [Coz causal profiler](http://coz-profiler.org/) looks interesting. According to [the related paper](https://cacm.acm.org/magazines/2018/6/228044-coz/fulltext), the authors used it to great effect in identifying a performance bottleneck in sqlite. [Related StrangeLoop Conference talk Youtube Video](https://www.youtube.com/watch?v=r-TLSBdHe1A)

You build with `-ldl` and then add `COZ_PROGRESS_NAMED("name for progress point")` in a few spots in the c code (make a Python wrapper for this and insert it in benchmarks?), then apparently it points you to lines (not just the ones you marked IIUC), and it can make a graph of "optimizing this bit by x% improves overall performance by y%". They seem to be advertising it as uniquely useful for multithreaded apps, but it looks like they also talk about single-threaded uses. Disclaimer: I've never used this before.

**Comment by gvanrossum** [comment]
@brandtbucher tried coz last week and reported that it flagged lines for which we couldn't understand what would be wrong with them. We concluded that it's probably not useful for us (the example from the talk certainly sounds like it's more helpful for multi-threaded apps). If you're interested in proving us wrong, please give it a try and report back here!
