### ISSUE TITLE
Specialized eval loops for categories of functions

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#17]
Here's an idea I had during discussions with Guido about his "add-opcodes" (super-instructions) branch (#16).  The key observation is that many functions (i.e. code objects) could be grouped by different sets of common characteristics.  Then, for each of those groups we could derive an eval loop implementation that is optimized for that group of code objects.

(FYI, this relates to @markshannon's idea about [generated code for the eval loop](#5).)

The approach would look something like the following.

During core development:

1. analyze a large amount of Python code (characteristic of target workloads)
2. identify classes of functions with common characteristics ("numeric ops", "string ops", "object manipulation", "only set X of opcodes", etc.)
3. for each category, generate an eval loop implementations with targeted optimizations (the normal eval loop is default)

At runtime:

1. compiler identifies execution class for the current code object (and flags it)
2. in `_PyEval_EvalFrameDefault()` (or maybe in `_PyEval_EvalFrame()`) we pick the eval loop that corresponds to the code objects flag

There are other factors to consider, (e.g. the cache-level impact of switching between multiple eval loop implementations) but let's start with the high-level idea.

**Comment by markshannon** [comment]
Multiple interpreter loops are going to be very unfriendly to the icache, and almost certainly slower.
There is no mechanism to choose the interpreter, or specification of how they would differ.
Can we close this?

**Comment by gvanrossum** [comment]
How certain are you that a typical function execution doesn't completely
void the icache whenever an excursion in the runtime (maybe as simple as
PyObject_GetAttr) is made? IOW do we care about the icache at the scale of
function executions?

**Comment by markshannon** [comment]
I'm not certain about anything regarding what CPUs do with their caches.

**Comment by markshannon** [comment]
I'm closing this as there is nothing actually to be done here.
