### ISSUE TITLE
restore benchmarking machine to released pyperformance

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#173]

**Comment by gvanrossum** [comment]
Please communicate more. Did you do something, was it already fixed, or have you rejected the task?

**Comment by ericsnowcurrently** [comment]
Sorry about that.  The pyperformance repo our benchmarking host uses was set at the wrong commit.  I did a git checkout to set it to the right commit: 6484a40909312f373c8cfa8c05faec592288abb3 (the "1.0.2" release).
