### ISSUE TITLE
pyperformance release

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#174]
* [x] arrange release of pyperformance (main branch), with @pablogsal
* [x] update benchmarking machine to use the release
* [ ] update speed.python.org benchmark host to use the release (@pablogsal)
    * #252

**Comment by ericsnowcurrently** [comment]
https://github.com/python/pyperformance/issues/118

**Comment by ericsnowcurrently** [comment]
There was a bug in the release: https://github.com/python/pyperformance/issues/120.  So we'll have to do another.

**Comment by gvanrossum** [comment]
Can we get a more recent status update?

**Comment by ericsnowcurrently** [comment]
@pablogsal made the release and I need to update our benchmarking machine to use it.

**Comment by gvanrossum** [comment]
And "our benchmarking machine" is the machine under your desk? Who is going to update speed.python.org? I presume it's Pablo, but I think it's your responsibility that it is going to be done.

**Comment by ericsnowcurrently** [comment]
> And "our benchmarking machine" is the machine under your desk?

Correct.

> Who is going to update speed.python.org? I presume it's Pablo, but I think it's your responsibility that it is going to be done.

Correct.  I'll add a checkbox above.
