### ISSUE TITLE
Reading list

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#2]
Please add your favorite references!

Two things on HHVM (2018, so fairly recent):
- video: https://www.youtube.com/watch?v=P58g--fPNDM&ab_channel=PLDI2018
- paper: https://research.fb.com/wp-content/uploads/2018/04/hhvm-jit-a-profile-guided-region-based-compiler-for-php-and-hack.pdf

Mark Shannon writings:
- HotPy (2): https://sites.google.com/site/makingcpythonfast/
- A faster CPython: https://github.com/markshannon/faster-cpython
- Ph.D thesis: http://theses.gla.ac.uk/2975/

Victor Stinner writings:
- Faster CPython: https://faster-cpython.readthedocs.io/index.html
- FAT Python: https://faster-cpython.readthedocs.io/fat_python.html

**Comment by markshannon** [comment]
[Producing Wrong Data Without Doing Anything Obviously Wrong!](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.163.8395)

**Comment by ericsnowcurrently** [comment]
"USING PYTHON FOR MODEL INFERENCE IN DEEP LEARNING", DeVito et al (Facebook AI Research)

https://arxiv.org/abs/2104.00254

The most relevant aspects, for our project, are their coverage of a popular class of Python workloads (PyTorch) and their approach to CPU parallelism using CPython.

Overall, they cover a lot of interesting details that extend to many parts of Python core development and to the Python packaging ecosystem.  Most notably:

* a popular class of Python workloads (PyTorch)
* embedding CPython
* running multiple interpreters in the same process with CPU parallelism
* interpreter isolation
* solutions for package dependency resolution
* packaging PyTorch models for efficiency

**Comment by gvanrossum** [comment]
A very detailed post on perf improvements for .NET 6:

https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/

**Comment by gvanrossum** [comment]
Copy-and-Patch Compilation:

https://arxiv.org/pdf/2011.13127.pdf
