### ISSUE TITLE
Remove opcode ROT_FOUR

### ISSUE THREAD

**Issue by iritkatriel** [faster-cpython/ideas#200]
It is not used anywhere.

**Comment by corona10** [comment]
Similar discussion:
https://bugs.python.org/issue929502

**Comment by iritkatriel** [comment]
Thanks, that’s interesting. But I think now it’s no longer used at all.

**Comment by brandtbucher** [comment]
Note that `ROT_N(4)` (heavily used by pattern matching) still gets peepholed into the more efficient `ROT_FOUR`, so it does still appear in real compiled output.

I'm still okay with this change, though, since it's a pretty arbitrary decision where to stop using hardcoded rotation instructions and start using `ROT_N`, now that we have it. But still, something to consider when making this change.

**Comment by iritkatriel** [comment]
I see. Do the pyperformance benchmarks use pattern matching?

**Comment by gvanrossum** [comment]
They don't, because they were written long ago.

**Comment by iritkatriel** [comment]
@brandtbucher can you suggest a good microbenchmark to assess the difference between rot_four and rot_n(4)?

**Comment by brandtbucher** [comment]
Sure! This generates and executes 3 `ROT_N(4)` instructions on `main`:

```py
match (None, None, None, None):
    case (a, b, c, None):
        pass
```

**Comment by iritkatriel** [comment]
About 10% slower. 

ROT_FOUR:

./python.exe -m timeit "match (None, None, None, None):" "    case (a, b, c, None):" "        pass"
5000000 loops, best of 5: 49.2 nsec per loop

ROT_N(4):

```
./python.exe -m timeit "match (None, None, None, None):" "    case (a, b, c, None):" "        pass"
5000000 loops, best of 5: 54.6 nsec per loop
```

**Comment by brandtbucher** [comment]
Interesting. This generates the exact same code, but with the 3 `ROT_N(4)`s removed:

```py
match (None, None, None, None):
    case (None, a, b, c):
        pass
```

I'm curious, can you time that on the same machine? Subtracting that baseline from the other two should tell us exactly how much faster ROT_FOUR is vs ROT_N.

**Comment by iritkatriel** [comment]
./python.exe -m timeit "match (None, None, None, None):" "    case (None, a, b, c):" "        pass"
5000000 loops, best of 5: 42.7 nsec per loop

**Comment by iritkatriel** [comment]
I guess there is some N from which the memcpy beats the sequence of get-set. 

Did you measure the difference between the memcpy and a loop? Maybe for smaller Ns a loop will be faster.

**Comment by brandtbucher** [comment]
Wow, so `ROT_FOUR` is almost twice as fast as `ROT_N(4)`. That's more than I would have thought.

> Did you measure the difference between the memcpy and a loop? Maybe for smaller Ns a loop will be faster.

Nope, never tried. But now I sort of want to!

(And I'm still okay with this change, for the reasons mentioned earlier. Your call on whether to go ahead with it!)

**Comment by iritkatriel** [comment]
> (And I'm still okay with this change, for the reasons mentioned earlier. Your call on whether to go ahead with it!)

I'll wait for @markshannon to have a look. I don't know how much it buys us, and there is some cost (although not something that will show up in pyperformance).

**Comment by brandtbucher** [comment]
Yeah, that's doable. It just requires more bookkeeping in the compiler (and gets trickier with or-patterns that may store names in different orders). The stack use could also grow quite a bit with more complex patterns.

There's also the idea of using "fake names" a la comprehensions:

```
STORE_FAST(.a)
STORE_FAST(.b)
STORE_FAST(.c)
STORE_FAST(.d)
POP_JUMP_IF_NOT_NONE(<fail>)
LOAD_FAST(.a)
STORE_FAST(a)
LOAD_FAST(.b)
STORE_FAST(b)
LOAD_FAST(.c)
STORE_FAST(c)
LOAD_FAST(.d)
STORE_FAST(d)
...
<fail>
DELETE_FAST(.a)
DELETE_FAST(.b)
DELETE_FAST(.c)
DELETE_FAST(.d)
```

...which generates more code, but keeps stack use down and makes the or-pattern problem simpler.

But this is all beside the point. Bottom line is that `ROT_FOUR` makes some patterns a bit faster, but everything still works fine without it. There are much larger gains to be made by rewriting the pattern compiler to process patterns in parallel (my weekend project, at the moment).

**Comment by iritkatriel** [comment]
> There are much larger gains to be made by rewriting the pattern compiler to process patterns in parallel (my weekend project, at the moment).

Might be worth adding a pattern matching benchmark to pyperformance so you can track progress on that.

**Comment by brandtbucher** [comment]
> Might be worth adding a pattern matching benchmark to pyperformance so you can track progress on that.

I started writing some a while back (still trying to come up with a good benchmark for mapping patterns, though):

https://github.com/brandtbucher/patmaperformance

**Comment by iritkatriel** [comment]
The discussion about ROT_XXX continues on https://github.com/faster-cpython/ideas/discussions/228.
