### ISSUE TITLE
Work towards semi-formal semantics

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#208]
While complete formal semantics for Python are neither achievable not all that useful, I have some ideas around this topic that I'd like to put in writing. I will be borrowing freely from Brett Cannon's [syntactic sugar](https://snarky.ca/tag/syntactic-sugar/) series of blog posts.

I've now marked this as an Epic. There are at least two sub-tasks:

- [x] [Work out detailed rules for scopes and write a blog post about it](https://github.com/faster-cpython/ideas/issues/249).
- [ ] [Work out execution semantics and write it up](https://github.com/faster-cpython/ideas/issues/261).

**Comment by ericsnowcurrently** [comment]
FWIW, I read through most of your drafts and it makes sense.  Cool stuff!

**Comment by gvanrossum** [comment]
Oh, thanks! I am now thinking that I want to define some kind of "virtual machine" that we can use as a definite compilation target. This would be a tiny language that is much simpler to describe (or maybe you just have to believe it, like axioms in math). E.g. it could have

- functions with a fixed number of arguments, with static argument and return types
- static class definitions (like `$Result`)
- static methods, but no dynamic overrides
- statically typed locals
- assignment to locals and to attributes
- function calls with a fixed number of arguments
- A way to hand-waive about undefined behavior (e.g. hashing, I/O, and the code in code objects)

Such a language could be statically compiled to C so we'd (in theory) have an executable spec.
To actually execute it we would have to define the runtime and fill in the undefined blanks.

We'd also separately have to specify the symbol table part of the compiler -- e.g. exactly how does the compiler determine what's a local. (Do assignments inside dead code count? IMO yes.)

And probably other stuff I'm missing.

**Comment by ericsnowcurrently** [comment]
Sounds interesting.  It also reminds me a bit of similar musings by @brettcannon (recently), @ambv (relatively recently) and VanL (years ago), as well as RPython.

**Comment by gvanrossum** [comment]
I quote Brett extensively. :-) Can you dig up links to the musings by the other two? I have no recollection of either.

**Comment by ericsnowcurrently** [comment]
With Van, it was a conversation I had with him at PyCon UK in 2014. 🙂

Łukasz gave a keynote at PyLondinium a couple years ago: https://www.youtube.com/watch?v=KDXhu4rxTNY&t=965 (at about 16 minutes).

**Comment by ericsnowcurrently** [comment]
Also, here's a paper that @davidmrdavid pointed me at:  http://cs.brown.edu/research/plt/dl/lambda-py/lambda-py.pdf.

**Comment by gvanrossum** [comment]
Ooh, that's a very interesting and very relevant paper. Too bad that I cannot stand their notation (figures 1-7). But I should definitely try to understand what I can, and reference it (even though I have no intention to publish a paper).

**Comment by davidmrdavid** [comment]
Yeah the notation in these papers can be quite annoying: an impenetrable wall of greek letters and symbols. If it helps, I know the authors of that project quite well and I would suspect that they'd be interested in helping out in any formalization efforts for Python, even if it's just by clarifying what them and others have done in the literature. If this is of interest, please do let me know and I can pull them into this thread :-)

**Comment by brettcannon** [comment]
> I am now thinking that I want to define some kind of "virtual machine" that we can use as a definite compilation target... Such a language could be statically compiled to C so we'd (in theory) have an executable spec. To actually execute it we would have to define the runtime and fill in the undefined blanks.

Interesting! We could probably even get two independent implementations in C and Rust as your `$Result` type is pretty much a direct mapping to Rust's [`Result` type and approach to error propagation](https://doc.rust-lang.org/stable/book/ch09-02-recoverable-errors-with-result.html) which might make the mapping easy enough to make that second implementation not feel burdensome.

**Comment by gvanrossum** [comment]
Maybe I got it from Rust? I definitely didn't invent it here. Though it was sparked by something Mark said about exceptions being carried as global (well, thread) state and all the problems that causes. I doubt Rust invented it either though, it's a simple ADT like in Haskell.

Honestly I'd be happy with just an implementation in Rust (who needs another CPython :-).

**Comment by gvanrossum** [comment]
FWIW I am trying to read through the lambda-py paper, and I am beginning to recognize some of the things it's talking about.

(OT: I sometimes wonder why academics never send me their work. Authors of Python books used to offer me review copies or PDFs, but this has never happened with academic papers. I was shocked when I found out that there *are* academics writing about Python! :-)

**Comment by markshannon** [comment]
Shouldn't this be a discussion rather than an issue?

**Comment by gvanrossum** [comment]
It’s an issue because I am actively working on it, so it must me in the Project board.

**Comment by gvanrossum** [comment]
(Although right now I'm stuck because I can't figure out how to generate Tiny Python code for `yield` inside a loop or try-except (see [here](https://github.com/gvanrossum/gvanrossum.github.io/commit/0d286bb2932264dd2685a404ebada59c58d882f7)).

**Comment by johnthagen** [comment]
@gvanrossum 

> Honestly I'd be happy with just an implementation in Rust 

In case you haven't seen, there is a community effort to create a Python interpreter in Rust: https://github.com/RustPython/RustPython

**Comment by merwok** [comment]
I’m sure people here are aware of that, but that’s not what this ticket is about 🙂

**Comment by saulshanabrook** [comment]
I also was looking at the recent work by @koehlma to develop a formal operational semantics for Python: ["An Executable Structural Operational Formal Semantics for Python"](https://arxiv.org/abs/2109.03139) which I believe is implemented in https://github.com/koehlma/rigorous/tree/master/rigorous/semantics/python

**Comment by gvanrossum** [comment]
Thanks for the link. I am afraid it is too formal for me to follow. :-(
Any suggestion on how to get something useful out of that?

**Comment by arhadthedev** [comment]
What's about [ECMAScript specification](https://tc39.es/ecma262/) as an inspiration? It's built around four __concepts__:

1. The whole runtime is described not in lengthy prose but in concise high level algorithms with parameters and return values.

1. An abstract syntax tree is used not to create a linear bytecode but for immediate execution. Each AST node is treated as a live in-heap object of a class associated with a grammar rule that spawned the node. Methods of these classes are called "semantics", their pseudocode is defined by a specification and they may call various "semantics" of children AST nodes. To execute a program, you need to call:
    1. an "Early Errors semantic" of a root AST node to catch nonsyntax compilation errors,
    2. then an "Evaluation semantic" of a root AST node to actually "execute" a program.

1. Calling a standard library method also invokes an algorithm. In other words, *Evaluation* semantic of *CallExpression* AST node does not prescribe a compiler to generate some call but immediately invokes another pseudocode chunk described in a specification.

1. Non-algorithmic runtime features like call stack frames and variable scopes are described as live objects with specified fields. The only difference a specification makes with normal objects is not listing them in a global scope so they are not visible to user code.

Of course, this hypothetical interpreter is used only to explain exact behavior. It *may* be used to create a reference interpreter for comparison testing. However, real inplementations just maintain behavior (with corner cases) visible from the outside world.

**Comment by gvanrossum** [comment]
Thanks @koelma, that's helpful! Clearly you put a lot of effort into this -- more than I expect I will be able to put into my own, which makes it unlikely that I will be able to complete it. The ECMAscript approach mentioned by @arhadthedev looks somehow related, as both approaches tie execution to the AST rather than going via bytecode. I might do a similar thing (targeting what I have termed TinyPython, without as yet defining it :-).

I have a concrete question. I am sure the answer is somewhere in your thesis, but I couldn't immediately find it. It is about side effects of the `__bool__()` dunder. Suppose I write
```py
if foo and bar: ...
```
where `foo` and `bar` are instances of a class whose `__bool__()` method has an observable side effect (let's say it prints a debug message).

We've had some internal discussions about whether it is guaranteed that `foo.__bool__()` and `bar.__bool__()` are each called at most once in this scenario. For example, one could easily produce bytecode that evaluates `foo and bar` by making the requisite calls and leaves the result (which must be either `foo` or `bar`) on top of the stack, at which point `if` pops that value off the stack and calls its `__bool__()` method, resulting in a second call to `foo.__bool__()` if `foo` is falsey.

OTOH the actual bytecode in all recent CPython implementations uses jumps and end up calling `foo.__bool__()` exactly once, and `bar.__bool__()` at most once.

I'd like to be able to *specify* that redundant calls are disallowed in this case by specifying that "bool(X and Y)" translates into "bool(X) and bool(Y)" even though normally "X and Y" translates into "X if not bool(X) else Y" (where bool() is the internal operation used to test for true or false, not the built-in bool() function).

How is this dealt with in your thesis? I can see on pp 83-84 how you capture the short-circuit semantics, but I don't understand how this connects to the behavior of 'if' on page 93. (Admittedly, it was only recently that I realized there's an issue here -- the PLR is not precise enough to capture the subtlety.)

PS. Do you have a black-and-white PDF? Some of the light-colored characters in your derivation rules are hard to read on my monitor (for my aging eyes, anyway).

**Comment by gvanrossum** [comment]
@koehlma Also thanks for the specific feedback on the lack of precision in the PLR. We should really update that document.

**Comment by koehlma** [comment]
> I'd like to be able to _specify_ that redundant calls are disallowed in this case by specifying that "bool(X and Y)" translates into "bool(X) and bool(Y)" even though normally "X and Y" translates into "X if not bool(X) else Y" (where bool() is the internal operation used to test for true or false, not the built-in bool() function).
>
> How is this dealt with in your thesis?

I am afraid, I was not aware of this subtlety. In case of my SOS semantics, `__bool__` is actually called twice on `X` if `bool(X) = false`. To fix this, one could introduce two new rules:

```
––––––––––––––––––––––––––––––––––––––––––––– BOOL-AND
 bool(X and Y) → (bool(X) ? bool(Y) : false)
```

```
––––––––––––––––––––––––––––––––––––––––––– BOOL-OR
 bool(X or Y) → (bool(X) ? true : bool(Y))
```

Here, `bool` is similar to your `$bool` intrinsic, I guess, and `true` and `false` are primitive booleans in contrast to `ref(True)` and `ref(False)` which are Python's object booleans. Now, one would also have to modify the rule `BOOL-EVAL` (p. 83) to not apply if the inner expression is `X and Y` or `X or Y`—which is possible in my meta-theoretical framework. Otherwise, the semantics would be non-deterministic which is esentially implementation freedom.

Anyway, I just checked what happens when `(X and Y) and Z` occurs not as a condition of an `if`. It appears that `__bool__` is also called only once on `X` if `bool(X) = false` in this case. So, the straightforward translation to `X if not bool(X) else Y` seems to be also broken in this case as it leads so something like:
```
L := X if not bool(X) else Y
L if not bool(L) else Z
```

Have you already considered this case?

My solution would be to treat `(X and Y) and Z` as `∀([X, Y, Z])` and analogously `(X or Y) or Z` as `∃([X, Y, Z])` (you may also call them `all` and `any`, respectivly, but this may lead to confusion with the equally named builtin functions). Now, of course, we still have to distinguish the `if` case from the normal case. To this end, we might want to give `∀` and `∃` an additional parameter `as_bool` indicating whether we are interested in a boolean.

An implementation of `∀` would then look something like this:
```python
def ∀(seq, as_bool = False):
    for item in seq:
        if not bool(item):
            if as_bool:
                return False
            return item
    else:
        if as_bool:
            return True
        # This assumes that the sequence is non-empty.
        return item
```
In my semantics one would then add a rule like
```
––––––––––––––––––––––––––––––––– BOOL-AND
 bool(∀(X)) → ∀(X, as_bool=True)
```
and modify `BOOL-EVAL` to not apply if the inner expression is `∀(X)`.

The expression `∃(X)` would be treated analogously.

>  The ECMAscript approach mentioned by @arhadthedev looks somehow related, as both approaches tie execution to the AST rather than going via bytecode. I might do a similar thing (targeting what I have termed TinyPython, without as yet defining it :-).

Yes, the main difference is that the ECMAScript Specification is essentially a big-step semantics while my SOS semantics is a small-step semantics. I just read through your ideas on TinyPython—very interesting. :) This seems to be a big-step semantics as well. The reason I went for a small-step semantics was that it allows me to handle generators nicely without resorting to some kind of complex and thus error-prone desugaring as done in the Lambda-Py paper. If I recall correctly, there also were quite some limitations on what could be done with the desugaring. In case of my SOS semantics, these restrictions do not apply and I do not have to justify any complex AST transformations.

I also desugar some constructs such as `for` loops and `try-except`. In fact, I seem to have come up with the same solution for `for` loops as @brettcannon. There are also plenty of edge cases to consider, e.g., `continue` or `break` in the `try` body or even the `finally` body of a `try-finally` in a loop.

In my semantics the rules always produce a successor state but also an *action* (usually denoted by α). The *action* is used for all kinds of non-local control flow (break, continue, exceptions, yield, return) as well as for other *side effects* (accessing the heap, calling a function, printing something, …).

Maybe something of this turns out useful for your endeavor as well. :)

> PS. Do you have a black-and-white PDF? Some of the light-colored characters in your derivation rules are hard to read on my monitor (for my aging eyes, anyway).

Unfortunately, no. :( In retrospect, colors with more contrast would have been better.

**Comment by gvanrossum** [comment]
Thanks for all the explanations! You have given me lots of food for thought. I like the idea of using generators to validate an approach (these are generally one of the most complex parts of Python's semantics, it appears).

Indeed, I had not considered `(X and Y) and Z` yet. (Our bytecode generator, of course, gets it right, because it uses a completely different approach. :-)

I need to look into the difference between small-step and big-step semantics.

**Comment by gvanrossum** [comment]
This turned out to be harder than I expected and as a work item I'm going to abandon it (maybe pick it up after 3.11 beta 1 is released). I've learned a lot though, and I found the papers to be very useful. I am impressed especially with @koehlma's work.
