### ISSUE TITLE
Pyperformance results?

### ISSUE THREAD

**Issue by ELind77** [faster-cpython/ideas#209]
Hi all, 

sorry if this isn't the right place to ask this, but I've been watching the github issues and I've seen multiple mentions of a benchmarking server with pyperformance running but I haven't seen a reference to where to find benchmark results for all of the different issues.  Is there somewhere that the community could see benchmark results? 

Best,

Eric

**Comment by gvanrossum** [comment]
It’s just speed.python.org.
