### ISSUE TITLE
More stats

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#233]
It is a bit embarrassing how little information we have to guide our work.
As well as decent profiles and traces, we can also learn a lot from custom counters.

We already have good numbers for specializations and instruction counts.
However we lack good numbers for:
* Objects:
  * How many allocations are served from freelists, how many could be?
  * How many objects have virtual dictionaries, how many dicts get created?
  * How many dictionaries get converted from split-keys to combined?
* Calls:
  * What portion of calls to Python functions are inlined? What portion of Python-to-Python calls? Of calls to generators?
  * How common are calls to builtin functions and classes that do not support vectorcall?
* Refcounting:
  * What fraction of refcount operation occur in the bytecode interpreter? How many of those are for pops and pushes?
  * What fraction of decrefs to zero are close in time to a matching allocation? (I don't know how to measure this, but I'd like to know the numbers)
 * Cycle GC:
   * What is the effectiveness of a collection? (Ratio of objects collected to objects visited)

Suggestions for more stats to gather are very welcome.

**Comment by brandtbucher** [comment]
> What fraction of decrefs to zero are close in time to a matching allocation? (I don't know how to measure this, but I'd like to know the numbers)

We could approximate this by bumping a second counter each time the refcount is changed in either direction, and check that counter at deallocation.

If the value of the second counter is less than 10 or so, we can call that a "barely used" object that might benefit from a freelist, etc.

**Comment by sweeneyde** [comment]
It might be nice to know exactly which DEOPT_IF branches are being taken the most, rather than just one `..._MISS` stat per instruction family.

**Comment by sweeneyde** [comment]
Can the dxpairs api be folded into the Py_STATS API so that the data there gets collected at the same time? Right now, if I understand right, `_opcode_stats.pair_count[256]` is currently unused.

**Comment by markshannon** [comment]
> Can the dxpairs api be folded into the Py_STATS API so that the data there gets collected at the same time? Right now, if I understand right, `_opcode_stats.pair_count[256]` is currently unused.

I don't think that dxpairs it is a useful stat. We have superinstructions for the top few pairs, and that seems sufficient.

However, given that someone's bound to complain if we remove it, we might as well add it to the opcode stats.

**Comment by markshannon** [comment]
> It might be nice to know exactly which DEOPT_IF branches are being taken the most, rather than just one `..._MISS` stat per instruction family.

Adding stats per `DEOPT_IF` might be a bit awkward, but adding them per specialized instruction is trivial. I'll do that.

**Comment by markshannon** [comment]
I'm closing this, and making a new issue for GC monitoring. All the other stats are done for now, apart from the freelists which I'm adding to https://github.com/faster-cpython/ideas/discussions/132

**Comment by markshannon** [comment]
https://github.com/faster-cpython/ideas/discussions/259
