### ISSUE TITLE
Optimizing `super().meth()` via adaptive superinstructions

### ISSUE THREAD

**Issue by Fidget-Spinner** [faster-cpython/ideas#242]
Please see https://github.com/faster-cpython/ideas/discussions/239 for the discussion and https://bugs.python.org/issue46564 for the BPO.

**Comment by Fidget-Spinner** [comment]
CPython PR is at https://github.com/python/cpython/pull/30992.

**Comment by gvanrossum** [comment]
Hi @Fidget-Spinner I'm a little confused about what you're saying at the end. I understand the PR (that won't ever be merged) saw a 2.2 speedup. After that, are you saying that in the main branch, super().meth() is now 10% slower than self.meth(), which is an improvement over that ratio for 3.10?

**Comment by Fidget-Spinner** [comment]
@gvanrossum  Sorry, I meant specifically in that PR, `super.meth()` is only 10% slower than `self.meth()`. In 3.10, it was around 2x slower.

On main, it should still be around 2x slower. Although we optimized `super()` with vectorcall support, we also optimized `self.meth()` via specialization. Most likely the latter outstrips the former.

**Comment by gvanrossum** [comment]
@Fidget-Spinner Do we still need this issue?

**Comment by Fidget-Spinner** [comment]
@gvanrossum Nope. Carl has has merged his version, so it's done.
