### ISSUE TITLE
[profiling] Add profiling instrumentation centered on the eval loop

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#25]
Here are the key boundaries:

* outside `_PyEval_EvalFrameDefault()`
* between start of `_PyEval_EvalFrameDefault()` and top of loop (setting up)
* between top of loop and dispatch
* handling an opcode
* between dispatch and bottom of loop
* between bottom of loop and returning (cleaning up)

**Comment by markshannon** [comment]
I think this is worth revisiting.
In order to direct our efforts we need to know where the virtual machine is spending its time.

This is relevant to both startup and general execution.

The text summary sounds useful, could we also get flamegraphs? I think they are a great way to visualize where time is being spent.

We should also generate results using `perf` or similar tool, to cross check that we are instrumenting the right things.

**Comment by ericsnowcurrently** [comment]
FWIW, I generated a flamegraph for `./python -c 'pass'`:

https://raw.githubusercontent.com/faster-cpython/ideas/main/flamegraph.svg

**Comment by gvanrossum** [comment]
Greetings from the Central European Timezone. :-)

Is there somewhere that describes what this particular flamegraph means?
(I've seen explanations of flamegraphs in general, but I'm not familiar
with the tool or methodology used to generate this particular one.)

**Comment by sweeneyde** [comment]
I ran what amounts to PyPerformance's bench_expand, bench_integrate, bench_sum, and bench_str benchmarks in a loop for about a minute with a PGO ("PGUpdate") build, and Visual Studio's Performance Profiler got me some results.

The hottest 15 functions:

**Function Name**|**Total CPU [unit, %]**|**Self CPU [unit, %]**
-----|-----|-----
\_PyEval\_EvalFrameDefault|58793 (99.79%)|15770 (26.77%)
call\_function|58793 (99.79%)|4045 (6.87%)
\_Py\_dict\_lookup|3262 (5.54%)|3019 (5.12%)
initialize\_locals|2329 (3.95%)|1468 (2.49%)
\_PyUnicode\_FromId|1422 (2.41%)|1422 (2.41%)
\_PyFunction\_Vectorcall|58793 (99.79%)|1299 (2.20%)
\_PyObject\_GenericGetAttrWithDict|24025 (40.78%)|1262 (2.14%)
\_PyObject\_Malloc|1314 (2.23%)|1219 (2.07%)
[External Call] vcruntime140.dll|1076 (1.83%)|1076 (1.83%)
\_Py\_DECREF|994 (1.69%)|994 (1.69%)
\_PyObject\_GetMethod|1521 (2.58%)|878 (1.49%)
tupledealloc|996 (1.69%)|878 (1.49%)
frame\_dealloc|881 (1.50%)|726 (1.23%)
PyObject\_GetAttr|25021 (42.47%)|711 (1.21%)
method\_vectorcall|58513 (99.31%)|678 (1.15%)

I also got a Line-by-line-profile of \_PyEval\_EvalFrameDefault, and VS shows it like this:
![image](https://user-images.githubusercontent.com/36520290/126882160-ed6570da-489e-4f97-b873-4451a527ae82.png)


I couldn't find a way to make VS dump the output as text, but here are 17 (low-quality, but at least mostly legible) screenshots of the results on the whole function 
https://imgur.com/a/WEHwFkr

**Comment by ericsnowcurrently** [comment]
> Is there somewhere that describes what this particular flamegraph means?
> (I've seen explanations of flamegraphs in general, but I'm not familiar
> with the tool or methodology used to generate this particular one.)

Flamegraphs are relatively new to me.  After a little digging, I found a good resource: https://www.brendangregg.com/flamegraphs.html.  This pointed me to https://github.com/brendangregg/FlameGraph, which is what I used to produce the flame graph.  As noted above, it involved generating data in a specific way using the linux "perf" tool and then passing that data through some scripts to produce the SVG file.

(Note that the SVG is better/interactive if you download it and then open the downloaded copy in your browser.)

As to what it means (from [the web page](https://www.brendangregg.com/flamegraphs.html#Summary)):

> The x-axis shows the stack profile population, sorted alphabetically (it is not the passage of time), and the y-axis shows stack depth, counting from zero at the bottom. Each rectangle represents a stack frame. The wider a frame is is, the more often it was present in the stacks. The top edge shows what is on-CPU, and beneath it is its ancestry. The colors are usually not significant, picked randomly to differentiate frames.

**Comment by ericsnowcurrently** [comment]
I just added https://github.com/faster-cpython/ideas/blob/main/flamegraph-20210726-1956.svg, which I generated:
* on our bare-metal benchmarking machine (instead of a VM)
* non-debug build
* with a max sample rate of 100,000hz

**Comment by ericsnowcurrently** [comment]
Observations (from both flame graphs):
* "perf" should be ignored so all the other percentages are actually proportionally higher
* the "swapper" (presumably loading from disk) takes a decent chunk of time - 23% on bare metal and 87% on VM
* a bunch of our functions are on the call stack during times that "main" is not, for unclear reasons

**Comment by ericsnowcurrently** [comment]
I found the problem with the stack size.  There's a kernel setting "kernel.perf_event_max_stack" that defaults to 127.  Changing this to 1000 gives us the proper graph.

**Comment by ericsnowcurrently** [comment]
I've opened #75 to dive into runtime startup/shutdown profiling.

**Comment by ericsnowcurrently** [comment]
We can circle back later (if we need it) to the specific instrumentation described in the original post above.
