### ISSUE TITLE
Deal with Pyston benchmarks failures on 3.11.

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#255]
When I ran the pyston benchmarks against 3.11 on our internal machine, only 3 of the 12 benchmarks ran successfully.  The failures need to be resolved.

succeeded:

* json
* pycparser
* thrift

failed dependencies:

* aiohttp - yarl, uvloop
* djangocms - Pillow
* gevent_hub - greenlet
* gunicorn - yarl, uvloop
* kinto - uWSGI (https://github.com/unbit/uwsgi/issues/2365)
* mypy - typed-ast
* pytorch_alexnet_inference - torch (pinned version is unsupported)

(Aside from uWSGI, all the dependencies should be fixed now and need their pinned versions updated.)

failed during benchmark run:

* flaskblogging - connection closed unexpectedly
* pylint - using `inspect.formatargspec()` (removed in 3.11)

**Comment by gvanrossum** [comment]
(What's the difference between #255, #256, #257.)

**Comment by ericsnowcurrently** [comment]
GitHub hiccup'ed.
