### ISSUE TITLE
Specialize `UNPACK_SEQUENCE`

### ISSUE THREAD

**Issue by brandtbucher** [faster-cpython/ideas#264]
https://github.com/python/cpython/pull/31240

**Comment by gvanrossum** [comment]
This isn't just for bm_unpack_sequence I hope? :-)

**Comment by brandtbucher** [comment]
> This isn't just for bm_unpack_sequence I hope? :-)

I'd probably commit the change even if it made that specific "use case" 100% slower. ;)
