### ISSUE TITLE
Stop using _Py_IDENTIFER() in extension modules.

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#279]
See https://bugs.python.org/issue46541#msg413246.

**Comment by ericsnowcurrently** [comment]
We can't get rid of `_Py_IDENTIFIER` until 3rd party extensions stop using it, so there is no hurry.  Let's just leave those modules alone for now.

**Comment by iritkatriel** [comment]
I think this can be close, the only remaining usages are in Modules/_testcapimodule.c.
