### ISSUE TITLE
Remove ob_shash from bytes object.

### ISSUE THREAD

**Issue by methane** [faster-cpython/ideas#290]
* Compared to str, bytes in dict key is less common.
* co_lnotab, co_linetable, co_columntable, co_endlinetable in code object wastes some RAM.

Since Cython use it, we need deprecation period.

**Comment by da-woods** [comment]
This can be disabled in Cython with by defining `CYTHON_USE_UNICODE_INTERNALS=0` (and in the longer-term can be disabled properly with a `PY_VERSION_HEX` guard) so it's not a serious problem to remove it.

**Comment by methane** [comment]
https://bugs.python.org/issue46864
