### ISSUE TITLE
Shadowcode

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#3]
This is a project by Dino Viehland at Facebook. It's on GitHub for anyone who knows where to look:
https://github.com/DinoV/cpython/commits/cpython/master/shadowcode

What I've gleaned so far:
- He's ripped out the existing inline caching and replaced it by something more general
- Instead, he's added several new opcodes that work with the cache
- For "hot" functions, he generates alternate bytecode that contains the new opcodes
- Bytecodes are substituted one-on-one, so he doesn't have to fix up jumps
- There's also code for profiling/instrumentation the use of the new opcodes
- More TBD

**Comment by markshannon** [comment]
Cinder has been open sourced, so this is now obsolete

**Comment by gvanrossum** [comment]
See https://github.com/facebookincubator/cinder
