### ISSUE TITLE
Let's do some comparative benchmarking

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#300]
We ought not be shy about how we are doing.
The word "faster" is the name of our project, after all. Let's show how much.

I would like a table like this on the front page of this project:

#### Performance relative to 3.10
| Benchmark suite    |  CPython 3.11 | Pyston | Pyjion | Cinder |
|---|---:|---:|---:| --:| 
| PyPerformance | 1.20 | ? | ? | ? |
| Pyston |   ? | 1.25? | ?  | ? |
|  ... | ... | ... | ... | ... |
|  ... | ... | ... | ... | ... |

A bit of healthy competition is good for everyone.
It might be good to include the numbers for PyPy, just to add some context.

We could also add GraalPython, if it doesn't waste too much time, as an antidote to this marketing nonsense: https://www.graalvm.org/python/

**Comment by kmod** [comment]
Hi, do you have any details on how exactly you collect your numbers? We (Pyston) want to make sure that we have the same methodology. 

In particular I'm not sure what build script you use for building CPython, as well as the build that you use as the baseline. For example we use the Ubuntu package as our baseline because we think that's what our potential users are currently using, but if we were to switch to using a self-compiled CPython as our baseline then our numbers would be slightly better.

**Comment by gvanrossum** [comment]
IIUC we just use
```
./configure --enable-optimizations
make
```
This enables PGO and LTO, and uses a subset of the stdlib test suite as the training set for PGO. (We know the latter is not ideal, but we would fix that by improving the training set used by the above two commands, not by using a different build script.)

**Comment by kmod** [comment]
Are you sure you don't pass `--with-lto`? `./configure --enable-optimizations` enables PGO but not LTO.

Also I noticed that a few of the pyperformance benchmarks are failing for cpython main (genshi, sqlalchemy_declarative, sqlalchemy_imperative), and they seem to just be excluded from the tables I've seen shared here. Again I don't really have a preference about what the exact definition of "the pyperformance benchmark suite" is, I just want to make sure I'm doing it the same way as you folks -- should we consider these benchmarks as part of the suite?

**Comment by gvanrossum** [comment]
I've been told by the folks who maintain the `configure` script that `--enable-optimizations` enables both PGO and LTO. If I'm wrong I think nobody on the Faster CPython team knew about this. Could this have changed in 3.10 or 3.11?

AFAIK @brandtbucher is working on getting the genshi BM to pass (and several Pyston BMs that also fail -- or maybe that's already done?). I'm not sure about the sqlalchemy BMs. Brandt?

**Comment by brandtbucher** [comment]
I usually pass both `--enable-optimizations` and `--with-lto`, since (as I understand it) the former *only* turns on PGO. I believe pyperformance has separate configuration options for each. The name is pretty confusing.

(FYI, I believe our benchmarking machine always enables both options).

**Comment by brandtbucher** [comment]
See [here](https://github.com/python/cpython/blob/3b0f1c5a710eff289dc44bec972dbaea353cc54f/configure.ac#L1521-L1524).

**Comment by brandtbucher** [comment]
> I'm not sure about the sqlalchemy BMs. Brandt?

Yeah, these failures are new, and I started tracking them earlier today. Discussion [here](https://bugs.python.org/issue46836#msg414279).

**Comment by kumaraditya303** [comment]
> I've been told by the folks who maintain the configure script that --enable-optimizations enables both PGO and LTO. If I'm wrong I think nobody on the Faster CPython team knew about this. Could this have changed in 3.10 or 3.11?

See https://bugs.python.org/issue45373

**Comment by corona10** [comment]
As the author of thinLTO feature, I can definitely say that we should pass the `--with-lto` separately.

* --with-lto: Will work as default LTO option (currently full LTO)
* --with-lto=full: use full LTO
* --with-lto=thin: use thin LTO.

Without these options, only PGO works for compiles.
see also what I did for the BOLT optimizer: https://github.com/faster-cpython/ideas/issues/224

**Comment by markshannon** [comment]
Pyston and Pyjion are now more dead parrot than unladen swallow.
Cinder has too different an execution model to make comparisons meaningful, although if the Cinder folks were to publish up-to-date numbers for pyperformance, I'd be interested.

**Comment by itamaro** [comment]
> Cinder has too different an execution model to make comparisons meaningful, although if the Cinder folks were to publish up-to-date numbers for pyperformance, I'd be interested.

What do you mean by "too different an execution model"?
Last time I tried producing up-to-date pyperformance numbers for cinder 3.10, I was unable to get it built with optimizations using the default toolchain we use for the open-source build, but that shouldn't be insurmountable!
If you're referring to the fact that even if we resolve that build issue we still end up with numbers for 3.10, and that's not reasonably comparable with numbers for main - then yeah, that would be a more fundamental difficulty :)

**Comment by MostAwesomeDude** [comment]
You should add the numbers for PyPy; somebody needs to do it. I estimated [here](https://lobste.rs/s/m55u77/pypy_has_been_quietly_working_for_me_for#c_lw5c6d) that PyPy would be about 3.6x faster than CPython, although an apples-to-apples comparison has yet to happen.
