### ISSUE TITLE
Inline caching

### ISSUE THREAD

**Issue by brandtbucher** [faster-cpython/ideas#310]
Discussion: #263
BPO: https://bugs.python.org/issue46841

In (rough) order:

- [x] https://github.com/python/cpython/pull/31543
- [x] https://github.com/python/cpython/pull/31575
- [x] https://github.com/python/cpython/pull/31591
- [x] https://github.com/python/cpython/pull/31618
- [x] https://github.com/python/cpython/pull/31622
- [x] https://github.com/python/cpython/pull/31640
- [x] https://github.com/python/cpython/pull/31663
- [x] https://github.com/python/cpython/pull/31664
- [x] https://github.com/python/cpython/pull/31671
- [x] https://github.com/python/cpython/pull/31709
- [x] https://github.com/python/cpython/pull/31742
- [x] https://github.com/python/cpython/pull/31780
- [x] https://github.com/python/cpython/pull/31817
- [x] https://github.com/python/cpython/pull/31888
- [x] https://github.com/python/cpython/pull/31901
- [ ] https://github.com/python/cpython/pull/31968
- [x] https://github.com/python/cpython/pull/32099
- [x] https://github.com/python/cpython/pull/32100
- [x] https://github.com/python/cpython/pull/32205
- [x] https://github.com/python/cpython/pull/32222
- [x] https://github.com/python/cpython/pull/92360
- [x] https://github.com/python/cpython/pull/92409
- [ ] https://github.com/python/cpython/pull/95694
- [ ] Reduce intermediate copying in `marshal`
- [ ] Check cache sizes earlier (in the compiler?)
- [ ] Add tests for adaptive/specialized/super instructions

**Comment by markshannon** [comment]
Sorry for not thinking this through earlier, but we might not want to quicken in-place.
https://github.com/faster-cpython/ideas/discussions/338

**Comment by mdboom** [comment]
Is there anything urgent we meant to do for these two?

> Update Doc/library/dis.rst
> Update Doc/whatsnew/3.11.rst

**Comment by brandtbucher** [comment]
> Is there anything urgent we meant to do for these two?
> 
> > Update Doc/library/dis.rst
> > Update Doc/whatsnew/3.11.rst

Not *urgent*, but `dis.rst` should probably have an entry for `CACHE` instructions. So should the "CPython bytecode changes" section of What's New. I'll get to these today.

**Comment by brandtbucher** [comment]
I also plan to close this issue and break out any actionable 3.12 list items into their own issues.

**Comment by mdboom** [comment]
Yeah -- sorry by "urgent" I mainly meant for 3.11.  I imagine doc changes are pretty much fair game even through the rc cycle, so still fine.
