### ISSUE TITLE
Investigate "Check if generated files are up to date" failures

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#341]
https://bugs.python.org/issue47146

**Comment by gvanrossum** [comment]
For example, https://github.com/python/cpython/runs/5719012664?check_suite_focus=true

I believe @markshannon and @brandtbucher were hypothesizing that `make -j8` somehow triggers this type of failure, suggesting a missing dependency in the Makefile.

**Comment by ericsnowcurrently** [comment]
https://github.com/python/cpython/pull/32162

**Comment by ericsnowcurrently** [comment]
Per https://github.com/python/cpython/pull/32134, looks like that fixed it.

**Comment by arhadthedev** [comment]
@ericsnowcurrently python/cpython#32162?

**Comment by ericsnowcurrently** [comment]
correct
