### ISSUE TITLE
Make virtual opcodes have negative values

### ISSUE THREAD

**Issue by iritkatriel** [faster-cpython/ideas#345]
### Discussed in https://github.com/faster-cpython/ideas/discussions/337

<div type='discussions-op-text'>

<sup>Originally posted by **iritkatriel** March 24, 2022</sup>

I think it would be good to change the type of struct instr's i_opcode from unsigned char to int, and make the virtual opcodes have ~~values > 256~~ negative values.  This way we are not wasting opcodes on the virtual ones, so we can add as many virtual ones as we want to improve clarity. Also, it will be easy to detect bugs where a virtual opcode was not converted before the bytecode is assembled.
</div>

**Comment by iritkatriel** [comment]
Virtual opcodes don’t appear in pycs. They are internal to the compiler.

**Comment by iritkatriel** [comment]
I've done that in [this PR](https://github.com/python/cpython/pull/32200), along with a change to is_jump to make it detect only jumps, and leave is_block_push for the exception setup opcodes. I think this makes the code clearer in a few places.

**Comment by arhadthedev** [comment]
Got it, then compression is really not needed. I just thought that `i_opcode` is used across all bytecode stages so its expansion affects bytecode files too.

**Comment by iritkatriel** [comment]
This is complete.
