### ISSUE TITLE
Create a standard data set of Python code

### ISSUE THREAD

**Issue by mdboom** [faster-cpython/ideas#360]
This may already exist in the team or elsewhere, so apologies if I'm retreading ground.

It would be useful to have a standard data set of Python source code to measure the effect of bytecode changes on size of bytecode, memory usage of code objects, etc.

This data set could probably be defined as "top N projects on PyPI on a given date". And then for convenience, provided as a single tarball available to the whole community so anyone could experiment with different changes.

**Comment by gvanrossum** [comment]
In https://github.com/faster-cpython/tools/tree/main/scripts are a few scripts that support this.

I wrote download_packages.py there to download the top N PyPI projects as gzipped tarballs. Othjer scripts like count_opcodes.py do various analyses on the downloaded project files (expanding tarballs searching for .py files and compiling them).

**Comment by mdboom** [comment]
Thanks.  I'll poke around in those scripts and probably end up just closing this.
