### ISSUE TITLE
Extra overhead in ctypes when setting argtypes

### ISSUE THREAD

**Issue by FreddieWitherden** [faster-cpython/ideas#372]
As observed in #370 there is quite a large amount of overhead associated with explicitly setting function argument types in the ctypes module.  This is due to:

https://github.com/python/cpython/blob/main/Modules/_ctypes/callproc.c#L1191

where for each argument we perform `v = t.from_param(v)` where `t` is the argument type.  Overhead therefore scales with the number of arguments.  Given most arguments are simple (integers, floats, pointers to structs, etc.) it should be possible to identify known `from_param` methods at the time the argument list is being set and tag them in a manner which enables the explicit method and object-creation functions to be elided at call-time.

**Comment by gvanrossum** [comment]
Sounds like you have a good grasp on this. Would you like to propose a PR?

**Comment by FreddieWitherden** [comment]
> Sounds like you have a good grasp on this. Would you like to propose a PR?

I'm a little tied up with work for the next month or so. However, if someone is interested in picking this up I have a rough idea of what needs doing.

I am reasonably convinced that in the case of simple arguments that it should be possible for argtype'd ctypes call to perform similarly to - if not better than - dynamic untyped calls.
