### ISSUE TITLE
Benchmark suggestion: deepcopy

### ISSUE THREAD

**Issue by eendebakpt** [faster-cpython/ideas#379]
At the python language summit @markshannon invited ideas for benchmarking. One python method that is currently not in the pyperformance benchmarks is `deepcopy` (at least not in the benchmarks that execute on my system).

In [#91610](https://github.com/python/cpython/pull/91610) (reimplement `deepcopy` in C) there is a simple benchmarking script for `deepcopy`. It is a simple execution of `deepcopy` on a `dict` and a `dataclass`. The benchmark is really simple (not a program), but in larger projects the cost of `deepcopy` was sometimes a significant part of the total execution time.

**Comment by ericsnowcurrently** [comment]
Would you mind opening an issue on [pyperformance](https://github.com/python/pyperformance/issues/new)?

**Comment by AlexWaygood** [comment]
> Would you mind opening an issue on [pyperformance](https://github.com/python/pyperformance/issues/new)?

Ah, should I update my blog post? I believe at the moment I have a sentence in there inviting people to open issues here if they have benchmarking suggestions, but maybe pyperformance would be better?

**Comment by ericsnowcurrently** [comment]
> > Would you mind opening an issue on [pyperformance](https://github.com/python/pyperformance/issues/new)?
> 
> Ah, should I update my blog post on Mark's talk? I believe at the moment I have a sentence in there inviting people to open issues here if they have benchmarking suggestions, but maybe pyperformance would be better?

Good catch!  It would probably be better to point them to the pyperformance tracker.  Perhaps @markshannon has a good reason for opening the issues here?  Otherwise, pyperformance would be better.

**Comment by AlexWaygood** [comment]
> Perhaps @markshannon has a good reason for opening the issues here? Otherwise, pyperformance would be better.

I've just listened back to the recording of the talk, and I don't think Mark actually specified which issue tracker would be best to suggest new benchmarks (he just said "please give us benchmark suggestions"), so I think this is entirely on me :)

I'll go ahead and update my article.

**Comment by AlexWaygood** [comment]
Fixed: https://pyfound.blogspot.com/2022/05/the-2022-python-language-summit_2.html

**Comment by ericsnowcurrently** [comment]
You're the best!
