### ISSUE TITLE
Add a job queue for running benchmarks

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#383]
This is important when we have more people running benchmarks on the one shared host.

**Comment by ericsnowcurrently** [comment]
done: faster-cpython/tools#18 and faster-cpython/tools#19

**Comment by gvanrossum** [comment]
Instructions?

**Comment by ericsnowcurrently** [comment]
You can keep using the same command as before.  For the additional functionality, run `jobs.py` instead of `run-bench.py`.  There are various subcommands for adding/running jobs and managing the job queue.
