### ISSUE TITLE
Upload recent benchmark results

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/ideas#384]
(for #334)

* [x] 3.11b1
* [x] 3.11b2
* [x] pyston benchmarks for 3.10
* [ ] ~missing weekly~

**Comment by gvanrossum** [comment]
@ericsnowcurrently Are the results truly comparable? I compared 3.10.4 with 3.11.0b2 and the geometric mean of the latter is 1.56 times faster. That feels off.

Here's what I ran (in `ideas\benchmark-results` after a `git pull`):
```
pyperf compare_to .\cpython-3.10.4-9d38120e33-fc_linux-42d6dd4409cb.json .\cpython-3.11.0b2-72f00f420a-fc_linux-42d6dd4409cb.json
```

**Comment by gvanrossum** [comment]
Even weirder:
```
pyperf compare_to .\cpython-3.11.0a3-2e91dba437-fc_linux-42d6dd4409cb.json .\cpython-3.11.0b2-72f00f420a-fc_linux-42d6dd4409cb.json
...
Geometric mean: 6.54x faster
PS C:\Users\gvanrossum\ideas\benchmark-results> pyperf compare_to .\cpython-3.11.0a3-2e91dba437-fc_linux-42d6dd4409cb.js
```

**Comment by ericsnowcurrently** [comment]
Hmm, I'll take a look tomorrow.

**Comment by gvanrossum** [comment]
Thanks!

**Comment by ericsnowcurrently** [comment]
I updated the result files today.

**Comment by gvanrossum** [comment]
Cool, this looks much better. So, 3.21b3 is 29% faster than 3.10.4, and 3.12 is already 2% faster than that!

**Comment by ericsnowcurrently** [comment]
Yeah, looking pretty good.
