### ISSUE TITLE
Add benchmark that makes measurable use of enum

### ISSUE THREAD

**Issue by mdboom** [faster-cpython/ideas#425]
We had an unexpected [regression in enum in the 3.11 cycle](https://github.com/python/cpython/issues/93910) and we know from [running the profiler over pyperformance](https://gist.github.com/mdboom/28c538cbdfb9fd9114a8eb0ce8aa1722) that none of the benchmarks spend a significant amount of time dealing with enums.

We should try to add a good benchmark that makes meaningful use of enums, ideally not just an enum microbenchmark, though.

**Comment by kmod** [comment]
Shameless plug -- it might be less than you want, but the pyston djangocms and flaskblogging benchmarks spend about 0.5-1% of their time in enum.py

**Comment by mdboom** [comment]
That's actually really helpful, @kmod.  I had been struggling to find something (just by poking around with Github code search).  This might get resolved by finishing #175 then.
