### ISSUE TITLE
Publish C-level coverage for the test suite

### ISSUE THREAD

**Issue by mdboom** [faster-cpython/ideas#426]
One thing we've learned from the [frame.setlineno set of issues](https://github.com/python/cpython/issues/94438) is that the C-level coverage of the test suite isn't perfect.

If we started publishing the C level coverage of the test suite somewhere that would help us to file bugs to proactively improve coverage of the test suite.

I've seen projects that do this on pull requests -- there is usually so much noise in the results that IME it's not terribly useful.  I think just a nightly (or even weekly) publishing of coverage results on `main` would go a long way, though.

It should be possible to do this with Github Actions.

**Comment by mdboom** [comment]
[This PR (on my own fork)](https://github.com/mdboom/cpython/pull/2) produced [this output](http://droettboom.com/cpython-coverage/).

**Comment by erlend-aasland** [comment]
An alternative (or supplement) to `lcov`, is using LLVM's [source-based code coverage](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html). The big advantage over `lcov` is branch coverage. I've found that very useful when increasing the sqlite3 extension module coverage.

**Comment by iritkatriel** [comment]
@erlend-aasland Can you share your commands/workflow?

**Comment by erlend-aasland** [comment]
> @erlend-aasland Can you share your commands/workflow?

Sure! For the record, I'm on macOS, using the XCode supplied toolchain.

1. Set both `CFLAGS` and `LDFLAGS` to `-fprofile-instr-generate -fcoverage-mapping`
2. configure and make
3. run the test suite (or most often, just the sqlite3 tests)
4. generate coverage results (see details)

<details>

```bash
#!/bin/sh
set -ve

MACOS_VER="12.2"
PY_MAJOR="3"
PY_MINOR="12"
PREFIX="build/lib.macosx-${MACOS_VER}-x86_64-${PY_MAJOR}.${PY_MINOR}-pydebug/"
SUFFIX="cpython-${PY_MAJOR}${PY_MINOR}d-darwin.so"

SQLITE_LIB="${PREFIX}/_sqlite3.${SUFFIX}"
BIN=$SQLITE_LIB  # python.exe, $SQLITE_LIB, etc.
PROFRAW=default.profraw
PROFDATA=default.profdata
SRC=Modules/_sqlite
REPORT=llvm-report
IGNORE="(clinic|Include)"
[llvm-report.zip](https://github.com/faster-cpython/ideas/files/9067651/llvm-report.zip)

llvm-profdata merge \
  -sparse $PROFRAW  \
  -o $PROFDATA

llvm-cov report                    \
  -ignore-filename-regex="$IGNORE" \
  -instr-profile=$PROFDATA         \
  $BIN                             \
  $SRC

llvm-cov show                      \
  -format=html                     \
  -output-dir=$REPORT              \
  -ignore-filename-regex="$IGNORE" \
  -instr-profile=$PROFDATA         \
  $BIN                             \
  $SRC

rm -f $PROFDATA
```

</details>

See [llvm-report.zip](https://github.com/faster-cpython/ideas/files/9067656/llvm-report.zip) for sample HTML output.

**Comment by erlend-aasland** [comment]
I've got a branch lying around where I've added llvm-cov support to configure/make. I'll see if I can restore it and rebase against main.

**Comment by mdboom** [comment]
> I've got a branch lying around where I've added llvm-cov support to configure/make. I'll see if I can restore it and rebase against main.

Sure, that would be very helpful.

**Comment by tiran** [comment]
FYI lcov can do branch coverage. It is just disabled by default. I have working code that generated branch coverage with GCC and LCOV.

I would like to see llvm-cov support in Makefile, too.

**Comment by tiran** [comment]
There is also https://github.com/gcovr/gcovr . It's a replacement for gcov/lcov/genhtml and written in our favorite language.

**Comment by mdboom** [comment]
Thanks for pointing out `lcov` with branch coverage. I'll generate that and compare that with `llvm-cov`.

Yeah, I agree on `llvm-cov` in the Makefile.  It's a bit tricky because everything else in the Makefile assumes you're using `gcc` on Linux.

As for gcovr, I had looked at it, but it doesn't seem like [anything it offers is really relevant](https://gcovr.com/en/stable/faq.html#what-is-the-difference-between-lcov-and-gcovr) and I thought it better to not add another moving part.  But if there's something specific it does that lcov doesn't let me know.

**Comment by tiran** [comment]
* GCOVR https://cheimes.fedorapeople.org/cpython/gcovr-report/coverage_details.html
* LCOV output with branch coverage https://cheimes.fedorapeople.org/cpython/lcov-report/

**Comment by mdboom** [comment]
Thanks for sharing those. Based on this, I think my entirely subjective thoughts are:

- The GCOVR view of branches is slightly more obvious than the LCOV one. (The same information is there).
- LLVM-COV still has one advantage which is produces better highlighting of the regions of subexpressions.  Look at [GCOVR](https://cheimes.fedorapeople.org/cpython/gcovr-report/coverage_details.frameobject.c.f1de0b7194da5b0cdf48379eca8678d7.html#l426) vs. [llvm-cov](http://[droettboom.com/cpython-coverage/llvm-coverage/coverage/home/mdboom/Work/builds/cpython/Objects/frameobject.c.html#L426) for example.

**Comment by tiran** [comment]
I agree with you. The llvm-cov output looks more modern and presents more information.

**Comment by lazka** [comment]
not sure if that is relevant/useful here, but coverage.py recently gained an option to export to lcov format, so you can merge C and Python coverage into one report. Example for a Python/C extension: https://gnome.pages.gitlab.gnome.org/pygobject/gi/index.html

**Comment by gvanrossum** [comment]
Should be closed as "not planned" instead?
