### ISSUE TITLE
Fix up presentation of performance results.

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#434]
Our presentation of performance results is a bit untidy and may be wrong.

The README includes a table of historical performance results. Ideally it would just include the latest results and a link to the historical data.

Something like this:

----

### Latest Performance Results

| Benchmark | release | commit | Speed (relative to 3.10.?)
|  --- | --- | --- | --- | 
| Pyperformance |  CPython 3.12.0a0 | c20186c397 | 1.31 |
| Pyston |  CPython 3.12.0a0 | c20186c397 | ??? |
| Spanish Inquisition |  CPython 3.12.0a0 | c20186c397 | Comfy chair |

_Link to table of historical numbers, methodology and hardware used._

---

The Pyston benchmark numbers we are reporting are *exactly* the same as the Pyperformance numbers. That doesn't seem likely.

**Comment by ericsnowcurrently** [comment]
I'm not opposed to improving the table.  It was meant to be a good starting point.

**Comment by ericsnowcurrently** [comment]
Regarding the Pyston benchmarks, I've manually hidden the table and [updated the tooling](https://github.com/faster-cpython/tools/pull/80) to hide it when results get uploaded.  We can circle back to the underlying problem at our convenience.

**Comment by mdboom** [comment]
I filed a separate bug for the Pyston results problem here: https://github.com/faster-cpython/ideas/issues/437

I'm already working on the table summary improvement separately from that.
