### ISSUE TITLE
Triage the open "performance" issues on cpython repo

### ISSUE THREAD

**Issue by iritkatriel** [faster-cpython/ideas#440]
There are 243 open issues with the "performance" label on cpython repo:

https://github.com/python/cpython/issues?q=is%3Aissue+is%3Aopen+label%3Aperformance+created%3A%3C2022-08-01+-label%3A3.12

**Comment by erlend-aasland** [comment]
Create a GH Project for it so it is easier to break it into smaller, manageable pieces.

**Comment by iritkatriel** [comment]
What would a project give us?

**Comment by erlend-aasland** [comment]
IMO[^1], it is easier to break a large pile of issues into smaller, more manageable pieces, mainly because of its grouping and filtering features, which are, in my opinion, superior to the filtering found in GitHub Issues.

[^1]: What works for me may not necessarily work out for others; this is just my personal opinion.

**Comment by iritkatriel** [comment]
I've assigned this to everyone on the team because it's a collective effort. 

The way I've been doing this is:

1. If the issue is still relevant, put a 3.12 label on it.
2. If it can be closed, close it.
3. If it's not really a performance issue, remove the performance label.
4. If I think it can be closed but not sure I ask a question and put a pending label (after a few weeks with no response we can close).


The link in the first comment of this issue excludes the 3.12 issues, so it shows only untriaged items.

**Comment by iritkatriel** [comment]
> > The way I've been doing this is:
> > 
> > 1. If the issue is still relevant, put a 3.12 label on it.
> 
> ... and put a `triaged` label on it, I presume:

No, I haven't been doing that.

**Comment by eendebakpt** [comment]
@iritkatriel There are also several performance related PRs that do not have the `performance` label. I performed a search on github using `is:pr is:open optimize -label:performance` and `is:pr is:open performance -label:performance` and hand selected the PRs that (in my opinion) could be either added to the 3.12+ performance related PRs or closed.
There are 16 of them, the links are included in the details below.

<details><summary>31-8-2022 potential performance PRs</summary>
https://github.com/python/cpython/pull/91566
https://github.com/python/cpython/pull/31871
https://github.com/python/cpython/pull/30992
https://github.com/python/cpython/pull/29109
https://github.com/python/cpython/pull/27782
https://github.com/python/cpython/pull/17669
https://github.com/python/cpython/pull/15363
https://github.com/python/cpython/pull/14771
https://github.com/python/cpython/pull/23496
https://github.com/python/cpython/pull/31936
https://github.com/python/cpython/pull/25518
https://github.com/python/cpython/pull/26160
https://github.com/python/cpython/pull/14306
https://github.com/python/cpython/pull/20288
https://github.com/python/cpython/pull/22759
https://github.com/python/cpython/pull/23213
</details>

**Comment by iritkatriel** [comment]
@eendebakpt Thanks for the list. I looked at a few and they seem related to open issues with the performance label, so they will be merged or closed when we look at those issues.

Perhaps the simplest way forward is to add the performance label to all those PRs, and then we will look at them just like we look at issues?

**Comment by eendebakpt** [comment]
> @eendebakpt Thanks for the list. I looked at a few and they seem related to open issues with the performance label, so they will be merged or closed when we look at those issues.
> 
> Perhaps the simplest way forward is to add the performance label to all those PRs, and then we will look at them just like we look at issues?

Sounds good!

**Comment by gvanrossum** [comment]
Looks like someone added the "performance" label to the PRs found by @eendebakpt. I now see

**Comment by gvanrossum** [comment]
Looks like someone added the "performance" label to the PRs found by @eendebakpt. The most inclusive query I can do is https://github.com/python/cpython/labels/performance which has 244 open issues.

How do I know which ones Irit hasn't already triaged? Only one of these has a 'triaged' label. 5 have 'pending'.

(I think Irit's original query was a tiny bit faulty, it excludes the three issues that have both 3.11 and 3.12 labels. Is the intention of the version labels to indicate the *first* version where the bug occurs?)

**Comment by iritkatriel** [comment]
The version labels are where we intend to fix the bug. It should be a version that has the issue and can still get the fix (at the time of labelling/relabelling).

I think it would be great to also have indication of where the bug was first observed, this was discussed during the GitHub migration but there is no convenient way to do this with labels so you need to figure it out from the issue’s history (comments and labels that have been removed). Thankfully the version labels were not removed altogether (that was suggested as well).

I filter on 3.12 because the purpose here is to review the old issues. Anything that has 3.12 on it was either recently created or recently triaged.

**Comment by iritkatriel** [comment]
Closing as complete.

Apart from 3 stdlib items that would require investigation by a subject matter expert, all the issues on the original list are now either closed or marked 3.12 or pending (i.e., we will decide one way or the other soon, based on responses).

Of the 243 items on the original list, we now have 150 marked performance that are left open.  Most of the others were closed, though there were some that remained open but lost the "performance" label because it was not actually relevant.
