### ISSUE TITLE
Advantages of saturating reference counts

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#452]
This relates to https://github.com/faster-cpython/ideas/discussions/125 and [PEP 683](https://peps.python.org/pep-0683/)

As well as being the best way to implement PEP 683, saturating reference counts also provides us with extra bits in the header for other optimizations and/or a more compact header.

A saturating reference count is more expensive than a non-saturating one, but it offers compensating performance advantages.

#### Storing the "size class" of smaller objects.

This needs 4 (or maybe 5) bits to store the size class of the object. Having the size class in the header means that we can serve the large majority of memory allocations from free-lists as we can very cheaply determine which free-list  the object belongs to.

It is possible that the speedups from this alone could balance the slowdowns from saturating reference counts.

#### Faster check for finalization. 

Having a "needs finalization" bit in the header saves work checking to see if an object needs finalization. Needs 1 bit.

#### Compact object headers and external weakrefs

https://github.com/faster-cpython/ideas/discussions/125#discussioncomment-2439106

We can reduce the size of the pre-header from 4 words to 2 by removing the weakrefs pointer and one of the GC header words

Instead of storing a pointer to an object's weakrefs in the object, which is almost always NULL, we can use a single bit to mark if an object has weakrefs, and store the weakrefs externally.

This has the nice side effect of allowing weakrefs to objects that currently don't support it, like lists and tuples.
(We still don't want to allow weakrefs to ints and floats, as that would prevent unboxing optimizations.)

There should be sufficient bits left in the top of the reference count word to store GC generation and some other information, allowing the GC header to be shrunk to a single word.

**Comment by ericsnowcurrently** [comment]
CC @eduardo-elizondo

**Comment by markshannon** [comment]
If we use 32 bit refcounts for all platforms, I think we can fake abi3 compatibility and still provide over 20 bits of flags for most objects.

### 64 architectures

Layout:
```C
int32_t flags; /* must be most significant half of the int64_t word */
int32_t saturating_refcount; /* The least significant half of the int64_t word */
PyTypeObject *type;
```
In order to fake abi3 compatibility the low 8 bits of the flags should serve as the sign-extension of the saturation bit, bit 8 should be unused to handle overflow.
This means that a refcount needs to off by about a trillion to be a problem. Resetting the refcount of `None` during GC should eliminate any realistic chance of error.
The most significant bit of the flags must be zero, so that the 64 bit refcount is positive.

### 32 bit architectures

For 32 bit architectures, we keep the refcount as before.
```C
int32_t refcount;  /* Not a saturating refcount, as 32 bit cannot overflow */
PyTypeObject *type;
```
This makes portability of code a bit of a problem, as we can't store information in the flags on 32 bit platforms.

Much of the information we want to store in the flags is already available, but slower to access, e.g. needs finalizing.
Other information only makes sense for objects with a pre-header, so we can store the flags in the pre-header.

This leaves only a few case where we want flags, but can't have them. Flags on `int`, `float`, and `str`, primarily.
It is really only the size class that matters in these cases, and that can be computed fairly cheaply by making the `Py_SIZE()` value for these objects all use the same format and dedicating a `tp_flags` bit to indicate that the `Py_SIZE()` value has the correct format.

**Comment by eduardo-elizondo** [comment]
Fortunately, the implementation of PEP 683 is already using [saturated reference counts](https://github.com/python/cpython/pull/19474/files#diff-87272721a5cf1cd9915d6f503f6a7bbefa2f26c935c7ce83ca78706afd0ad05aR81-R133)! I also had to handle the 32 bit architecture a bit different and had to drop saturation for this architecture.

Btw maybe this helps as a reference, in the python runtime that we started building years ago at the company, we also used 5 bits to [mark immediates](https://github.com/facebookexperimental/skybison/blob/trunk/runtime/objects.h#L228-L237]). Of course, creating fast paths and optimizations whenever there [was an immediate](https://github.com/facebookexperimental/skybison/blob/trunk/runtime/objects.h#L4682-L4691).

Regardless, yes, there are huge benefits of using saturated reference counts. Happy to see these proposals to make sure that the PEP 683 is implementation is done in a way that's compatible with all the suggestions made here

**Comment by eduardo-elizondo** [comment]
cc @colesbury

**Comment by markshannon** [comment]
@eduardo-elizondo
Using saturating refcounts is theoretically a breaking change, so needs to be part of the PEP.

**Comment by ericsnowcurrently** [comment]
> Using saturating refcounts is theoretically a breaking change, so needs to be part of the PEP.

The PEP covers defining ref count semantics more clearly (and specifically) in the docs.  Is there some other way that saturating refcounts would be a breaking change?

**Comment by markshannon** [comment]
We now have saturating refcount. Unfortunately the stable ABI prevents us from using the extra bits for now.
