### ISSUE TITLE
Enable `-fstrict-overflow`

### ISSUE THREAD

**Issue by matthiasgoergens** [faster-cpython/ideas#458]
Inspired by https://github.com/python/cpython/issues/96678#issuecomment-1243499193

At the moment we compile releases with `-fwrapv` which makes the code a bit safer, but disables certain optimizations.  From the GCC docs:

> This option instructs the compiler to assume that signed arithmetic overflow of addition, subtraction and multiplication wraps around using twos-complement representation. This flag enables some optimizations and disables others.

My experiments with running sanitisers seem to suggest that we are nearly already ready for `-fno-wrapv` (or `-fstrict-overflow` in general).  Doing so could lead to quite a few speedups, but we would need to be more careful with the code we write.

It might be worthwhile to get a few benchmarks.

**Comment by matthiasgoergens** [comment]
My plan right now is to adapt the build system so that only the modules that need it are build with -fwrapv, and the rest can be build with -fstrict-overflow.

We already have machinery that can add specific CFLAGS for specific modules only.

Perhaps the whole thing can be gated behind a configure flag.

If everything goes well, and this improves performance we can consider adding this functionality to one of the standard optimization options.

We can also work on making more modules -fstrict-overflow safe.

**Comment by ericsnowcurrently** [comment]
This is certainly worth exploring!  Consider moving the conversation to a [cpython issue](https://github.com/python/cpython/issues/new/choose) sooner rather than later, to get feedback from a broader audience.

**Comment by matthiasgoergens** [comment]
@ericsnowcurrently This grow out of the linked Cpython issue. But I can start a new issue, too?

**Comment by markshannon** [comment]
I agree, this should be a CPython issue.

**Comment by matthiasgoergens** [comment]
I'm closing this in favour of https://github.com/python/cpython/issues/96821
