### ISSUE TITLE
Extracting hints from the data to optimize the algorithms for sorting, searching and so on

### ISSUE THREAD

**Issue by vali19th** [faster-cpython/ideas#467]
I will use lists in my examples, but these ideas may also be applied to similar data structures.

1. When instantiating the list we could store two attributes `min` and `max`, and update them very cheaply on insert or assignment. Those would completely replace the need of iterating over the whole list when doing `min(my_list)` and might help with sorting. Storing the min/max index instead of the value might have some other benefits at practically no extra cost
2. An attribute `is_sorted` would skip the sorting entirely when True
3. An attribute `is_reversed` would hint to the interpreter that the sorting can be replaced with a call to `reversed()`. And also skip `sorted(..., reverse=True)`
4. Before sorting, do a run through the list to compute an "ascending score" that's calculated based on the percentage of times the next value is greater or equal to the current one. This will help the interpreter pick an algorithm optimized for different scenarios. 
4. Before sorting, do a run through the list and save the indexes where the run is interrupted to tell the algorithm where to look first. An extra optimization here would be use `x[i] < x[i+1]` to avoid an equality check. This helps with searching too because the "buckets" are sorted, so you do a binary search on individual buckets instead of the whole list
5. An attribute `changes_since_last_sort` that will only be incremented on insert and assignment, not deletion. This will hint to the sorting function that it should use an algorithm specialized for "almost sorted" lists
6. An attribute `has_duplicates`. Avoid unnecessary 'list(set(my_list))` calls for removing duplicates
6. If `has_duplicates == False` replace `sorted(my_list)` with `list(set(my_list))`. It is 4x faster on `range(10**5)` after `random.shuffle()`. If it's used internally and that part of the code does not necessarily need a list, skip casting the set back to a list
7. Before sorting, generate a `Counter()`, sort the keys, then reinsert the duplicates
8. Pick algorithms specialized for the list length or sort on slices first, then do a full sort. This will minimize memory consumption for very big lists and maybe help with the speed in some cases
9. Check the available system resources before sorting. Is there so much free RAM that we should pick the algorithm with higher RAM usage but higher speed?
10. Allow unstable sort. Maybe some things, at least internally, do not require a stable sort.
10. Use unstable sort if the key is the value itself

**Comment by gvanrossum** [comment]
I don't think this is within the scope of the Faster CPython project. Feel free to open an issue on the main CPython tracker, or start discussing these ideas on Python's Discourse forum (discuss.python.org).
