### ISSUE TITLE
If performance is the goal... 

### ISSUE THREAD

**Issue by LifeIsStrange** [faster-cpython/ideas#47]
You might as well consider the *technical excellence* of OpenJDK and join the growing universe of polyglot (transparently interoperable) languages https://github.com/oracle/graalpython
Revolutionary projects like this needs contributions!

They have already achieved SOTA performance for ruby, R and php!

**Comment by gvanrossum** [comment]
Getting the existing Python community to use GraalPython would be a hopeless task though.

**Comment by LifeIsStrange** [comment]
not more than getting it on pypy.

**Comment by pPanda-beta** [comment]
@LifeIsStrange indeed
its been 3 months now, I'm struggling to build grpc and pyarrow for pypy! No hopes so far!
