### ISSUE TITLE
Await-aware-function-calls (via cinder)

### ISSUE THREAD

**Issue by stuaxo** [faster-cpython/ideas#470]
(apologies if this is already implemented)
https://github.com/facebookincubator/cinder#await-aware-function-calls

I had a brief read through the readme of cinder, facebook/instagrams faster python fork, and this change looks like it the least complex to implement of all the changes.

(It's probably worth reading their readme to look at the others too).

**From the cinder readme:**

> Await-aware function calls
> The Instagram Server is an async-heavy workload, where each web request may trigger hundreds of thousands of async tasks, many of which can be completed without suspension (e.g. thanks to memoized values).
> 
> We extended the vectorcall protocol to pass a new flag, _Py_AWAITED_CALL_MARKER, indicating the caller is immediately awaiting this call.
> 
> When used with async function calls that are immediately awaited, we can immediately (eagerly) evaluate the called function, up to completion, or up to its first suspension. If the function completes without suspending, we are able to return the value immediately, with no extra heap allocations.
> 
> When used with async gather, we can immediately (eagerly) evaluate the set of passed awaitables, potentially avoiding the cost of creation and scheduling of multiple tasks for coroutines that could be completed synchronously, completed futures, memoized values, etc.
> 
> These optimizations resulted in a significant (~5%) CPU efficiency improvement.
> 
> This is mostly implemented in Python/ceval.c, via a new vectorcall flag _Py_AWAITED_CALL_MARKER, indicating the caller is immediately awaiting this call. Look for uses of the IS_AWAITED() macro and this vectorcall flag, as well as the _PyEval_EvalEagerCoro function.

**Comment by gvanrossum** [comment]
See https://github.com/python/cpython/issues/91121.
