### ISSUE TITLE
Stack effect of jumping -- how to express in DSL

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#481]
Our new DSL can express variadic stack effects using `array[oparg]` and even caters for conditions (`foo if (C-expression)`). But four opcodes (`SEND`, `JUMP_IF_FALSE_OR_POP`, `JUMP_IF_TRUE_OR_POP`, `FOR_ITER`) have different stack effects depending on whether they jump. How should we express that? New syntax or a magic  constant in `C-expression` above?

@markshannon

**Comment by gvanrossum** [comment]
I suppose we could just special-case an output stack effect of the form `res if (jump)` or `res if (!jump)`.

**Comment by iritkatriel** [comment]
I think this is resolved.
