### ISSUE TITLE
Generating code for the ceval loop/switch

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#5]
I'm collecting ideas for discussion, and this is the first one.

@markshannon Can you clear up any misunderstandings in my summary of your idea here?

IIUC Mark's idea is that we'd replace the big switch (and perhaps the loop around it as well) with code generated by a script from "opcode definitions", a bit similar to the way Argument Clinic works. Not sure if the opcode definition would be inline as Argument Clinic does or if they would be C snippets contained in a separate file.

Somehow this would allow us to create a version of the main loop that doesn't have to check for tracing on every opcode.

Not sure of other benefits yet.

**Comment by markshannon** [comment]
Currently, we seem to going down the manual route for adding new instructions. Which fine.
We may well want to factor out the code for automatic layout of the interpreter, and generation of IR for the compiler, but that can be done as needed.

**Comment by gvanrossum** [comment]
Reopening, see https://github.com/faster-cpython/ideas/issues/454#issuecomment-1251653405

**Comment by jneb** [comment]
Of course this is a great idea, making it easier to experiment with opcodes; especially when multiple people are trying thing out.
I guess it would also make it easier to change one or more of the operations, for example for the register based interpreter.

**Comment by gvanrossum** [comment]
We now have a working generator (see Tools/cases_generator). While there's a whole lot more to do, let's close this and discuss details in separate issues under the label epic-generator.
