### ISSUE TITLE
Is it possible to use SIMD instructions?

### ISSUE THREAD

**Issue by animalize** [faster-cpython/ideas#50]
x86:
https://www.officedaytime.com/simd512e/
https://software.intel.com/sites/landingpage/IntrinsicsGuide/

ARM:
https://developer.arm.com/architectures/instruction-sets/simd-isas/neon

**Comment by gvanrossum** [comment]
Hm, you'd first have to identify data for which parallel operations such as those would be useful. Perhaps things like string search might benefit, but I don't see a quick win for bytecode execution.

**Comment by ivoflipse** [comment]
Not bytecode execution, but here is one SIMD use case: https://github.com/simdjson/simdjson

Though I reckon these applications make more sense as extensions than changes to CPython

**Comment by animalize** [comment]
I saw zstd lib uses SSE2 instructions to match more than a dozen rows at a time, which is interesting. https://github.com/facebook/zstd/pull/2494

My first reaction was whether it can be used in `dict`. But later, I didn't think it would work.

**Comment by gvanrossum** [comment]
Yeah, if someone wants to speed up such a library they are welcome to try. But note that e.g. decompression modules typically wrap third party libraries written in C, so the changes would have to be submitted in that upstream code.

**Comment by bluss** [comment]
Those that are interested in SIMDifying dict could look at google's Swiss Table for inspiration - a hash table that uses SIMD for key lookup. I don't know how applicable it is to CPython's dict.
