### ISSUE TITLE
Avoid BUILD_TUPLE followed by RETURN_VALUE if UNPACK_SEQUENCE is right after CALL

### ISSUE THREAD

**Issue by lpereira** [faster-cpython/ideas#509]
This should avoid an unnecessary round-trip to the allocator in what I believe to be a very common case.

The way I see this being implemented is:

- Two new superinstructions: `BUILD_TUPLE__RETURN_VALUE` and `CALL__UNPACK_SEQUENCE`
- `CALL__UNPACK_SEQUENCE` sets a flag in the call frame
- `BUILD_TUPLE__RETURN_VALUE` sees if the flag is set:
    - If it's set, then it'll return from the function, leaving the stack in the way that `UNPACK_SEQUENCE` would have left it
    - If it's not set, would behave like the individual instructions

Thoughts on this?

**Comment by gvanrossum** [comment]
Looks like a winner for various common cases, let's ping @markshannon.

Could we do something similar for for-loops, e.g. `for i, x in enumerate(xs)`?

**Comment by lpereira** [comment]
`FOR_ITER` and `UNPACK_SEQUENCE` seems like another great candidate for something like this, but it looks like a big can of worms.  Would need to change how `tp_iternext()` works if I understood the machinery correctly.

**Comment by markshannon** [comment]
This is an optimization for the tier-2 (short-trace) optimizer.

The sequence
```
BUILD_TUPLE n
RETURN_VALUE
UNPACK_SEQUENCE n
```
Can be transformed into a bulk transfer of values from callee to caller.

**Comment by sweeneyde** [comment]
Adding `FOR_ITER_DICT_ITEMS` and `FOR_ITER_ENUMERATE` [here](https://github.com/python/cpython/pull/94096) did speed up `dict.items()` and `enumerate()` a bit, but for some reason, it slowed other things down when I measured (I may have measured incorrectly).

I'm not sure if we're still interested in virtual (index on the stack) iterators, but maybe that could be revisited.
