### ISSUE TITLE
 Port LOAD_ATTR from old opcache to PEP 659 adaptive interpreter

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#52]
There are many specializations for `LOAD_ATTR` that make sense. `LOAD_ATTR` in 3.10 only handles two, so we should have an easy win here.

Possible specializations are:
* Attribute is in instance dictionary
* Attribute is in a slot
* Attribute is a non-descriptor attribute of the class
* Attribute is a property
* Attribute is method
* The owner is a module

We will want dictionary keys versioning for several of the above.

**Comment by markshannon** [comment]
- [ ] Add dict keys version 
- [ ] Add `LOAD_ATTR_ADAPTIVE` and two specializations corresponding to existing `LOAD_ATTR`
- [ ] Split apart specialization for instance dicts into "known keys" and "probable index"
- [ ] Add specializations for module and class attributes

Specializing for properties needs support from call specialization machinery, so will need to wait for that.

**Comment by nilansaha** [comment]
Not sure if this is the right place for this but have you guys thought about adding a workflow that automatically benchmarks any PRs opened from this fork and reports it ? Could be really interesting to see speedups as they happen no matter how small. I think the entire Python community is incredibly excited for what is going down here.

**Comment by gvanrossum** [comment]
Probably better to open a separate issue. FWIW benchmarks are noisy enough that I think this isn’t going to be all that useful.

**Comment by bluss** [comment]
@nilansaha @gvanrossum Can the existing speed.python.org infrastructure be used for this? Ideally all the merged PRs would be followed-up there. Having a bot that can run the same benchmark set on a PR before it gets merged, would also be a great flow.
