### ISSUE TITLE
non-register arg to a register instruction

### ISSUE THREAD

**Issue by iritkatriel** [faster-cpython/ideas#527]
The cases generator currently generates ``arg = REG(opargi)`` statements for the inputs. We need a way to indicate in the DSL that an input is not a register index, but just a number (like a jump offset).

**Comment by gvanrossum** [comment]
Hm, for the stack machine this is not in the header at all, the body just uses oparg. Why can’t the register machine do this?

**Comment by iritkatriel** [comment]
It can, but the generator currently outputs the arg = REG(opargi), and we need it not to.

The easiest way for me to implement the jumps was to have the offset as oparg1 (it just reuses the current compiler code). Then the condition is in REG(oparg2).  So it would be sufficient if I could write something in the header that says "ignore oparg1, set cond = REG(oparg2)".

**Comment by iritkatriel** [comment]
I just pushed my JUMPS implementation, so you can see what I did.  (Some tests are failing due to peephole optimisations not working for these jumps yet).

**Comment by iritkatriel** [comment]
I'm not blocked on this, it seems to work (the offsets are small so it's not accessing crazy memory addresses?).

**Comment by gvanrossum** [comment]
Oh, seeing the code makes me realize that you can just name the first argument `unused` and then no code will be generated for it (or at least it shouldn't be -- this is how it is for the stack machine and for cache effects).

**Comment by iritkatriel** [comment]
Yes that works. Perfect.
