### ISSUE TITLE
Failure in test_general_eval in regmachine branch

### ISSUE THREAD

**Issue by iritkatriel** [faster-cpython/ideas#529]
I have this test failure, not sure what to think about it:

```
======================================================================
ERROR: test_general_eval (test.test_builtin.BuiltinTest.test_general_eval)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython-1/Lib/test/test_builtin.py", line 661, in test_general_eval
    self.assertEqual(eval('dir()', g, m), list('xyz'))
                     ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
TypeError: 'M' object does not support item deletion
```

``m`` is an instance of a mapping class which does not support deletions. The failure comes from [here](https://github.com/python/cpython/blob/main/Objects/frameobject.c#L1205), when the name is "$0" and the value is NULL. On main there is no "$0" and all the 'real' locals are non-NULL (so no deletion is attempted on this object).  Is it just that the test needs to change, or do we need to change something around the "$" variables?

**Comment by markshannon** [comment]
IMO, "$" variables should only exist in `dis` output. The locals should remain unchanged.
