### ISSUE TITLE
Improve tuple/list index-by-long speed

### ISSUE THREAD

**Issue by heeres** [faster-cpython/ideas#57]
This patch special-cases indexing of tuples and lists by a PyLong: https://github.com/heeres/cpython/commit/ade7269a89410b880bcfb1499e0d67d58c0d4171

Benchmark using:
```
import timeit
def x():
    a = list(range(16))
    for j in range(10000):
        a[j%16]
print('%.01f ms' % (timeit.timeit(x, number=1000)*1000))
```
As baseline, the loop with a `pass` instruction is timed at 120ms.
Without the patch, time is 446ms (456ms) with `a` defined as a tuple (list)
With the suggested patch, time is about 325ms for both tuple/list. Subtracting the time for the loop with a `pass`, this means the indexing is performed about 35% faster. Since we're not accounting for the modulo operation in this calculation, my guess would be somewhere between 40-45%.

The culprit is the rather complex PyNumber_AsSsize_t function, which performs a few calls and some reference juggling even in case of a simple PyLong.

If the digit size would be increased, the fastest path could apply to even more cases than it does now.

**Comment by gvanrossum** [comment]
Cool, that's probably something we could approach more systematically once we've got Quickening working (#27).

**Comment by markshannon** [comment]
Quickening is now working :slightly_smiling_face: 

> If the digit size would be increased, the fastest path could apply to even more cases than it does now.

I think digits are large enough at 30 bits (on 64 bits machines). There aren't many lists or tuples with more than a billion elements.

**Comment by markshannon** [comment]
This is a subset of https://github.com/faster-cpython/ideas/issues/59
