### ISSUE TITLE
 Implement BINARY_SUBSCR specialization "family" for PEP 659 adaptive interpreter

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#59]
Immediately obvious specializations are:
`list[int]`
`tuple[int]`
`dict[any]`

Binary subscript is not that common, so this might be marginal, but it is worth investigating.
Specialization of third-party classes, specifically numpy arrays, is also worth thinking about.

**Comment by iritkatriel** [comment]
See https://bugs.python.org/issue26280.

**Comment by iritkatriel** [comment]
See https://github.com/python/cpython/pull/27043

**Comment by markshannon** [comment]
@iritkatriel did you attempt to gather stats for any larger programs?
I'm wondering if there any further specializations that you thought might be worthwhile, or whether we should close this issue.

**Comment by iritkatriel** [comment]
I haven't yet.  I'm working on a PR to expose specialisation stats in python so we can more easily do this analysis (including deltas). 

What would the specialisation for a third party type like numpy array look like?

**Comment by markshannon** [comment]
> What would the specialisation for a third party type like numpy array look like?

Off the top of my head, with no evidence whatsoever...
A direct call to the underlying C function, maybe?
If the index were a integer then maybe call the `tp_as_sequence->sq_item` function directly?

**Comment by markshannon** [comment]
@iritkatriel shall we close this as done for now.
We can always open a new issue for improvements to `BINARY_SUBSCR` later.

**Comment by iritkatriel** [comment]
Sure.
