### ISSUE TITLE
Make bytecodes.c the source of all truth for instructions

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#591]
The source of truth about instructions is currently in several places: bytecodes.c has the instruction definitions, which includes stack and cache effects; opcode.py, which has numeric values for "public" instructions (but not for specialized instructions, super-instructions or micro-instructions).

A problem with this approach is that the cache definitions are repeated in multiple places that must be kept in sync manually:
- In the form of cache effects in bytecodes.c, e.g.
  ```py
          inst(CALL_PY_EXACT_ARGS, (unused/1, func_version/2, method, callable, args[oparg] -- unused)) {
  ```
- In opcode.py, as two tables: `_specializations` has
  ```py
      "CALL": [
          "CALL_PY_EXACT_ARGS",
          ...
       ],
  ```
  and `_cache_format` has
  ```py
      "CALL": {
          "counter": 1,
          "func_version": 2,
      },
  ```
- Additionally, bytecodes.c references `INLINE_CACHE_ENTRIES_CALL` which defined in pycore_code.h
  ```c
  typedef struct {
      uint16_t counter;
      uint16_t func_version[2];
  } _PyCallCache;
  
  #define INLINE_CACHE_ENTRIES_CALL CACHE_ENTRIES(_PyCallCache)
  ```
So that's three separate places that define the same structure (a 16-bit counter and a 32-bit func_version).

There are several separate scripts that take opcode.py and generate various other files: opcode.h, pycore_opcode.h, pycore_intrinsics.h (all generated by generate_opcode_h.py), opcode_targets.h (generated by makeopcodetargets.py).

A possible streamlining of the process could start by generating (most of) the contents of opcode.py from bytecodes.c, so these don't have to be kept in sync manually. (Generating the cache struct definitions is a bit more complicated, alas.)

### Update

Another reason to generate the numeric values of opcodes from bytecodes.c is the Tier 2 interpreter, which interprets micro-ops rather than bytecode ops. This requires some place that defines the numeric values of the micro-ops (even though they aren't stable, all internal tools need to agree on their numeric values). The collection of micro-ops is effectively set by the contents of bytecodes.c, so we might as well generate the micro-op values there. From there it's a logical conclusion to do the same for bytecode op values.

**Comment by markshannon** [comment]
I think this is all done.

We have some code in `optimizer_bytecodes.c` which describes how to optimize uops, but all the other hand-written code is now machine generated from bytecodes.c
