### ISSUE TITLE
New Paper from Mozilla

### ISSUE THREAD

**Issue by cfbolz** [faster-cpython/ideas#630]
There's been a very recent paper by Mozilla about "CacheIR", which reminded me a little of the upcoming uops (linear IR, the operations replace higher level ones, with guards, constructed after getting feedback from the runtime types, also speeds up interpreter). I thought you might be interested: https://dl.acm.org/doi/10.1145/3617651.3622979

**Comment by markshannon** [comment]
Thanks Carl.

The CacheIR does looks similar to our uops and to [some of the ideas I've been looking at for handling specialization of `LOAD_ATTR` and `CALL`](https://github.com/faster-cpython/ideas/issues/447), but more coherent and principled.

**Comment by Fidget-Spinner** [comment]
Added to our papers doc in the root folder.
