### ISSUE TITLE
Is it possible to implement automatic function inlining in CPython?

### ISSUE THREAD

**Issue by bobqianic** [faster-cpython/ideas#636]
In Python, every function call has a very significant overhead. I know Python is a dynamic language, but is it possible to implement **automatic function inlining** in CPython? I'm not very familiar with CPython, and my question might be a bit naive. Please understand. Thank you!

**Comment by gvanrossum** [comment]
It would be better to ask your question on a user forum, maybe the help or ideas category on discuss.python.org. Note that *this* tracker is mostly used for discussing advanced ideas for optimizing Python. In that context, it's likely that eventually some functions will automatically inlined.
