### ISSUE TITLE
Faster startup -- Experiment A

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#64]
This is a placeholder for a description of Experiment A (see https://github.com/faster-cpython/ideas/issues/32#issuecomment-878517764)

(For code see https://github.com/gvanrossum/cpython/tree/pyco)

**Comment by gvanrossum** [comment]
Looking over the diff for things to incorporate into experiment C (#64), I realized that we have PY_LOCAL_AGGRESSIVE disabled at the top of ceval.c. This should probably be re-enabled inside #ifdef NDEBUG before running perf tests.

**Comment by gvanrossum** [comment]
FWIW, there are a number of similarities between the format used here (never fully documented) and that in Dino's [icepack experiment](https://github.com/facebookincubator/cinder/tree/cinder/3.8/Experiments/icepack). (Note that Dino documents everything in pyice.py.)

**Comment by markshannon** [comment]
@gvanrossum can this closed, or moved to a discussion? (Likewise for all the other "Experiment" issues)

**Comment by gvanrossum** [comment]
Let's close this -- I spent considerable time on this but in the end it felt it was the wrong approach.
