### ISSUE TITLE
Explain these POP_JUMP_IF_FALSE/POP_JUMP_IF_TRUE timings

### ISSUE THREAD

**Issue by iritkatriel** [faster-cpython/ideas#68]
It seems that jumping is consistently faster than not jumping. Can we explain this, or am I doing something wrong?

iritkatriel@Irits-MBP cpython % ./python.exe -m timeit -s "x=False" "'1' if x else '0'"
20000000 loops, best of 5: 13.9 nsec per loop
iritkatriel@Irits-MBP cpython % ./python.exe -m timeit -s "x=True" "'1' if x else '0'"
20000000 loops, best of 5: 15.1 nsec per loop

```
>>> dis.dis("'1' if x else '0'")
  1           0 LOAD_NAME                0 (x)
              2 POP_JUMP_IF_FALSE        4 (to 8)
              4 LOAD_CONST               0 ('1')
              6 RETURN_VALUE
        >>    8 LOAD_CONST               1 ('0')
             10 RETURN_VALUE
```

I see this on windows and Mac.

Also - with x = 0/1 (so PyObject_IsTrue is called):

```
iritkatriel@Irits-MBP cpython % ./python.exe -m timeit -s "x=0" "'1' if x else '0'"
20000000 loops, best of 5: 16.3 nsec per loop
iritkatriel@Irits-MBP cpython % ./python.exe -m timeit -s "x=1" "'1' if x else '0'"
20000000 loops, best of 5: 17.9 nsec per loop
```

Also - if I change the condition to be "if not x" then it uses POP_JUMP_IF_TRUE, and again jumping is faster than not jumping:

```
iritkatriel@Irits-MBP cpython % ./python.exe -m timeit -s "x=0" "'1' if not x else '0'"
20000000 loops, best of 5: 17.8 nsec per loop
iritkatriel@Irits-MBP cpython % ./python.exe -m timeit -s "x=1" "'1' if not x else '0'"
20000000 loops, best of 5: 16.5 nsec per loop
```

**Comment by gvanrossum** [comment]
I have no idea. Maybe the pgo somehow decided that jumping is more likely? Because possibly it is -- lots of code does "if rare error condition: handle error", where a jump is expected, so maybe pgo finds out that the jump instructions usually jump, and optimizes that. @markshannon -- does that sound likely?

**Comment by markshannon** [comment]
It sounds plausible, but that means little when it comes to hardware. I have no idea, TBH.

I suspect those timings will change as a result of https://github.com/python/cpython/pull/27167.

**Comment by markshannon** [comment]
One other possibility is that the branches are sufficiently close together, or in some other way dependent on layout, such that the predictions interfere.

**Comment by markshannon** [comment]
Anyway, I don't think there is much we can about this. 
Feeling free to reopen if someone discovers what's going on.
