### ISSUE TITLE
Deegen: A JIT-Capable VM Generator for Dynamic Languages

### ISSUE THREAD

**Issue by Fidget-Spinner** [faster-cpython/ideas#707]
By Haoran Xu and Fredrik Kjolstad (Authors of Copy and Patch), they present a natural follow-up to their baseline JIT, with a second-tier JIT.

https://arxiv.org/pdf/2411.11469

**Comment by Fidget-Spinner** [comment]
@brandtbucher this paper also covers an improved Copy-and-Patch technique!

**Comment by markshannon** [comment]
Thanks for the link.

We should add a "papers" file to make it easier to find them (and not have so many open issues)
