### ISSUE TITLE
Specializations

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#74]
This is a meta issue for tracking which bytecodes have been specialized, need to be specialized, need to be improved, or aren't worth specializing.

## Completed

* LOAD_GLOBAL #51
* BINARY_MULTIPLY

## Done, but could be improved

* LOAD_ATTR #52 
* BINARY_OP
* BINARY_SUBSCR #59 
* STORE_ATTR #53 
* LOAD_METHOD #81
* STORE_SUBSCR

## In progress

* CALL_NO_KW

## To do

* CALL_KW

## Needs more data

Before more optimizing these, we need to know how well they will specialize

* FOR_ITER #67
* FORMAT_VALUE #61

## Not going to do

* All bytecodes whose behavior does not depend on the value(s) operated on, e.g. LOAD_FAST

**Comment by markshannon** [comment]
## Latest stats
13 Aug 2021 https://github.com/python/cpython/commit/230403a6a19042b174374c3825904d2e857f38b0
### Summary:
Opcode | Percentage specialized |  Notes
 ----- | ------ | ------
BINARY_SUBSCR | 53% | Not so good. Almost all misses are in two kinds; we should specialize those.
LOAD_ATTR | 82% | We want >90% for this. There are three or four kinds to consider specializing.
LOAD_GLOBAL | 99.4% | Excellent -- Nothing to do here.
STORE_ATTR | 91% | Good enough, maybe worth adding one more kind.
### Stats
```
binary_subscr:
    deferred:  1479500755 53.1%
       deopt:      623380 0.0%
         hit:  1305270025 46.8%
        miss:     1872955 0.1%
 unquickened:     1989874 0.1%
  specialization_success:      871934
  specialization_failure:    22586209
    kind  8:  3534113 15.6%
    kind  9:    76550 0.3%
    kind 10: 18975546 84.0%
load_attr:
    deferred:   645855401 16.2%
       deopt:     1525705 0.0%
         hit:  3276705716 82.0%
        miss:    58651531 1.5%
 unquickened:    15924427 0.4%
  specialization_success:      929543
  specialization_failure:    10243758
    kind  1:     3653 0.0%
    kind  2:  2748255 26.8%
    kind  4:  1785688 17.4%
    kind  5:     1344 0.0%
    kind  7:     8228 0.1%
    kind  8:  1741176 17.0%
    kind 10:   945222 9.2%
    kind 11:   579054 5.7%
    kind 12:   167794 1.6%
    kind 13:   656990 6.4%
    kind 14:   234797 2.3%
load_global:
    deferred:    11900975 0.5%
       deopt:      410891 0.0%
         hit:  2523103597 97.9%
        miss:     2681250 0.1%
 unquickened:    38473210 1.5%
  specialization_success:     2200458
  specialization_failure:           0
store_attr:
    deferred:    51562929 7.1%
       deopt:      137038 0.0%
         hit:   660448917 91.2%
        miss:     8609802 1.2%
 unquickened:     3581501 0.5%
  specialization_success:       68221
  specialization_failure:     1113525
    kind  1:    28496 2.6%
    kind  2:   109762 9.9%
    kind  4:   406608 36.5%
    kind  8:   163123 14.6%
    kind 11:    27618 2.5%
    kind 12:    22901 2.1%
    kind 13:     1389 0.1%
    kind 14:    11537 1.0%
```

**Comment by iritkatriel** [comment]
The two common fail cases of binary_subscr are:
SPEC_FAIL_LIST_NON_INT_SUBSCRIPT (8) and SPEC_FAIL_NOT_TUPLE_LIST_OR_DICT(10).

The first is presumably list with slice. The second could be many things.

**Comment by iritkatriel** [comment]
What benchmark are these stats from?

**Comment by markshannon** [comment]
From pyperformance.

**Comment by markshannon** [comment]
When adding (or removing) the odd bytecode in the past some core devs have seemed worried that we might run out of bytecodes.
While this is implausible for normal bytecodes, it might be an issue for specialized bytecodes.
So here is a summary estimate of how many bytecodes we will need for specialization at the very most.
 
Opcode | Specializations
 -------- | ----------
LOAD_GLOBAL | 3
BINARY_SUBSCR | 7
LOAD_ATTR | 10 
STORE_ATTR | 7
BINARY_ADD | 6
INPLACE_ADD | 7
BINARY_MUL | 3
INPLACE_MUL | 3
Other BINARY | 6
LOAD_METHOD | 6
FOR_ITER | 6
CALL_FUNCTION |  9
CALL_FUNCTION_KW | 9 
CALL_METHOD |  8
CALL_METHOD_KW | 8 
Total | ~100

Which is a lot, but that still leaves ~40 spare. So we aren't going to run out of opcodes.

I suspect it won't be that many, and there is a lot of potential code sharing between `CALL_FUNCTION`, `CALL_FUNCTION_KW`, `CALL_METHOD`, `CALL_METHOD_KW`.

**Comment by iritkatriel** [comment]
We can also have EXTENDED_OPCODE for rare opcodes.

**Comment by gvanrossum** [comment]
Yeah, and e.g. LOAD_ASSERTION_ERROR will be folded into LOAD_COMMON_CONSTANT.

**Comment by gvanrossum** [comment]
Here's a tidbit of interesting info from the Pyston Discord server:

- our JIT is handwritten using dynasm. llvm is only used during compilation of the pyston executable itself to generate type specific versions of runtime functions (used by quickening) so we don't have to write them by hand like cpython3.11. 
- this allows us to easily have many hundreds of them because we don't have to to keep them manually up to date - they will just get generated during the build process.
- here is a recent commit which adds a few more of this specializations (=traces). It adds traces for things like 'list()', 'int(float)', 'dict()',...
https://github.com/pyston/pyston/pull/114/commits/b6f49a56cbfe2e5cd46abdc3f7f2cac4ee7d3085

That sounds like an interesting approach to attempt in the future.

**Comment by markshannon** [comment]
The following table lists all instructions, whether they can be specialized, whether it is worth specializing them, and the status of the work on specializing them.


 Instruction | Specializable? | Worth doing? | Status
 ---- | ---- | --- | --- 
 BEFORE_ASYNC_WITH | :white_check_mark: | ? | 
 BEFORE_WITH | :white_check_mark: | ? | 
 BINARY_ADD | :heavy_check_mark: |  |  >90% hits on benchmarks. Considered done for now.
 BINARY_MULTIPLY | :heavy_check_mark: |  |  >90% hits on benchmarks. Considered done for now.
 BINARY_OP | :heavy_check_mark: | To do | 
 BUILD_CONST_KEY_MAP | :x: |  | :black_circle:
 BUILD_LIST | :x: |  | :black_circle:
 BUILD_MAP | :x: |  | :black_circle:
 BUILD_SET | :x: |  | :black_circle:
 BUILD_SLICE | :x: |  | :black_circle:
 BUILD_STRING | :x: |  | :black_circle:
 BUILD_TUPLE | :x: |  | :black_circle:
 CALL_FUNCTION | :heavy_check_mark: |  |  Partly done.
 CALL_FUNCTION_EX | :heavy_check_mark: |  |  To do
 CALL_FUNCTION_KW | :heavy_check_mark: |  |   To do
 CALL_METHOD | :heavy_check_mark: |  |   To do
 CALL_METHOD_KW | :heavy_check_mark: |  |   To do
 COMPARE_OP | :heavy_check_mark: |  |  Combine with following jump?
 CONTAINS_OP | :white_check_mark: | ? | 
 COPY | :x: |  | :black_circle:
 DELETE_ATTR | :white_check_mark: | ? | 
 DELETE_DEREF | :x: |  | :black_circle:
 DELETE_FAST | :x: |  | :black_circle:
 DELETE_GLOBAL | :white_check_mark: | ? | 
 DELETE_NAME | :white_check_mark: | ? | 
 DELETE_SUBSCR | :white_check_mark: | ? | 
 DICT_MERGE | :x: |  | :black_circle:
 DICT_UPDATE | :x: |  | :black_circle:
 DUP_TOP | :white_check_mark: | ? | 
 DUP_TOP_TWO | :white_check_mark: | ? | 
 END_ASYNC_FOR | :white_check_mark: | ? | 
 FORMAT_VALUE | :white_check_mark: | ? | 
 FOR_ITER | :white_check_mark: | ? | 
 GEN_START | :x: |  | :black_circle:
 GET_AITER | :white_check_mark: | ? | 
 GET_ANEXT | :white_check_mark: | ? | 
 GET_AWAITABLE | :white_check_mark: | ? | 
 GET_ITER | :white_check_mark: | ? | 
 GET_LEN | :white_check_mark: | ? | 
 GET_YIELD_FROM_ITER | :white_check_mark: | ? | 
 IMPORT_FROM | :white_check_mark: | ? | 
 IMPORT_NAME | :white_check_mark: | ? | 
 IMPORT_STAR | :white_check_mark: | ? | 
 INPLACE_ADD | :white_check_mark: | ? | 
 INPLACE_MULTIPLY | :white_check_mark: | ? | 
 INPLACE_OP | :white_check_mark: | ? | 
 IS_OP | :x: |  | :black_circle:
 JUMP_ABSOLUTE | :x: |  | :black_circle:
 JUMP_FORWARD | :x: |  | :black_circle:
 JUMP_IF_FALSE_OR_POP | :x: |  | :black_circle:
 JUMP_IF_NOT_EXC_MATCH | :white_check_mark: | ? | 
 JUMP_IF_TRUE_OR_POP | :x: |  | :black_circle:
 LIST_APPEND | :white_check_mark: | ? | 
 LIST_EXTEND | :white_check_mark: | ? | 
 LIST_TO_TUPLE | :white_check_mark: | ? | 
 LOAD_ASSERTION_ERROR | :white_check_mark: | ? | 
 LOAD_ATTR | :heavy_check_mark: |  ~80% hits on benchmarks. Needs improvement | 
 LOAD_BUILD_CLASS | :white_check_mark: | ? | 
 LOAD_CLASSDEREF | :x: |  | :black_circle:
 LOAD_CLOSURE | :x: |  | :black_circle:
 LOAD_CONST | :white_check_mark: | ? | 
 LOAD_DEREF | :x: |  | :black_circle:
 LOAD_FAST | :x: |  | :black_circle:
 LOAD_GLOBAL | :heavy_check_mark: |  |  Done
 LOAD_METHOD | :heavy_check_mark: |  ~80% hits on benchmarks. Needs improvement | 
 LOAD_NAME | :white_check_mark: | ? | 
 MAKE_CELL | :x: |  | :black_circle:
 MAKE_FUNCTION | :white_check_mark: | ? | 
 MAP_ADD | :white_check_mark: | ? | 
 MATCH_CLASS | :white_check_mark: | ? | 
 MATCH_KEYS | :white_check_mark: | ? | 
 MATCH_MAPPING | :white_check_mark: | ? | 
 MATCH_SEQUENCE | :white_check_mark: | ? | 
 NOP | :x: |  | :black_circle:
 POP_EXCEPT | :white_check_mark: | ? | 
 POP_EXCEPT_AND_RERAISE | :x: |  | :black_circle:
 POP_JUMP_IF_FALSE | :x: |  | :black_circle:
 POP_JUMP_IF_TRUE | :x: |  | :black_circle:
 POP_TOP | :white_check_mark: | ? | 
 PRINT_EXPR | :white_check_mark: | ? | 
 PUSH_EXC_INFO | :white_check_mark: | ? | 
 RAISE_VARARGS | :x: |  | :black_circle:
 RERAISE | :x: |  | :black_circle:
 RETURN_VALUE | :x: |  | :black_circle:
 ROT_FOUR | :x: |  | :black_circle:
 ROT_N | :x: |  | :black_circle:
 ROT_THREE | :x: |  | :black_circle:
 ROT_TWO | :x: |  | :black_circle:
 SETUP_ANNOTATIONS | :white_check_mark: | ? | 
 SET_ADD | :white_check_mark: | ? | 
 SET_UPDATE | :white_check_mark: | ? | 
 STORE_ATTR | :heavy_check_mark: |  | 
 STORE_DEREF | :x: |  | :black_circle:
 STORE_FAST | :x: |  | :black_circle:
 STORE_GLOBAL | :heavy_check_mark: |  | 
 STORE_NAME | :white_check_mark: | ? | 
 STORE_SUBSCR | :heavy_check_mark: |  | 
 UNARY_INVERT | :white_check_mark: | ? | 
 UNARY_NEGATIVE | :white_check_mark: | ? | 
 UNARY_NOT | :white_check_mark: | ? | 
 UNARY_POSITIVE | :white_check_mark: | ? | 
 UNPACK_EX | :x: |  | :black_circle:
 UNPACK_SEQUENCE | :x: |  | :black_circle:
 WITH_EXCEPT_START | :white_check_mark: | ? | 
 YIELD_FROM | :x: |  | :black_circle:
 YIELD_VALUE | :x: |  | :black_circle:

**Comment by gvanrossum** [comment]
What’s the difference between a green check mark and a frayed out one?

**Comment by brandtbucher** [comment]
Thanks for putting this together. Some thoughts:
- `GET_LEN`/`MATCH_CLASS`/`MATCH_KEYS`: Yup, clear candidates for specialization. I have some pattern matching `pyperf` benchmarks that I was working on a couple of months ago... it might be worth dusting those off and seeing what sort of improvement we can get. Probably lower priority, though, since obviously any work here won't move `pyperformance` at all.
- `MATCH_MAPPING`/`MATCH_SEQUENCE`: I doubt that we'd see any significant improvement with these, right? The current implementation is already *super* streamlined.
- `UNARY_INVERT`/`UNARY_NEGATIVE`/`UNARY_NOT`/`UNARY_POSITIVE`: Do you think it's worth exploring combining these into a single `UNARY_OP` instruction?

**Comment by brandtbucher** [comment]
> What’s the difference between a green check mark and a grayed out one?

It looks like ✔️ means "already specialized" and ✅ means "can be specialized".

**Comment by markshannon** [comment]
`Specializable` is now just :heavy_check_mark: or :x:.
I've also corrected several bytecodes.

**Comment by markshannon** [comment]
>     * `MATCH_MAPPING`/`MATCH_SEQUENCE`: I doubt that we'd see any significant improvement with these, right? The current implementation is already _super_ streamlined.

I've updated the table.

>     * `UNARY_INVERT`/`UNARY_NEGATIVE`/`UNARY_NOT`/`UNARY_POSITIVE`: Do you think it's worth exploring combining these into a single `UNARY_OP` instruction?

It might well be worth combining `UNARY_INVERT`/`UNARY_NEGATIVE`/`UNARY_POSITIVE`, but not `UNARY_NOT` as that is not a slot operator.

`-int`, `-float` and `~int` might well be worth specializing for.

**Comment by sweeneyde** [comment]
There are more detailed stats about STORE_SUBSCR [here](https://github.com/faster-cpython/ideas/issues/105#issuecomment-950210953), which I took before opening the specialization PR.

In particular, numbers are somewhat thrown off by the use of `bytearray[int]=...` in regex compilation, and especially by Scimark's use of `array.array[int]=...`, which I'm convinced says more about the particulars of pyperformance than about Python code in general.

I can open a PR to add some of those stats more permanently into the specialization code.

**Comment by markshannon** [comment]
We are now gathering stats automatically, most of the easy specialization are done, and the remaining have their own issues.
