### ISSUE TITLE
Regular object layout

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#80]
Accessing the `__dict__` of an object takes a bit of pointer chasing and computation.
The code to get the address of the `__dict__` is as follows:
(assuming we have already checked whether this object can have a dict)
```C
    Py_ssize_t dictoffset = tp->tp_dictoffset;
    if (dictoffset < 0) {
        /* Compute size of object */
        Py_ssize_t tsize = ...
        dictoffset += size;
    }
    dictptr = (PyObject **) ((char *)obj + dictoffset);
```
Given how often we access instance attributes, this overhead is significant

What we would like is:
```C
    dictptr = (PyObject **) ((char *)obj + CONSTANT;
```

**Comment by markshannon** [comment]
Since not all objects have a `__dict__` we cannot simply put the dictionary at a fixed offset after the header without leaving holes in small objects like ints and floats.

Since any object that has a dictionary can be part of a cycle, it must have a GC header. 
Therefore, we can put the dictionary directly before the GC header and there will be no gap.

## Simple object without GC header, e.g. an int.
![minimal](https://user-images.githubusercontent.com/9448417/128163386-4c82f2dd-abe5-474d-80e2-b336b525dd2a.png)

## Object that may be part of cycle, but without `__dict__`, e.g. a list.
![cyclic](https://user-images.githubusercontent.com/9448417/128163837-280155ac-f7b4-4e56-a16f-08e5c42f7f03.png)

## Object with a `__dict__`

![popo](https://user-images.githubusercontent.com/9448417/128162687-529afa91-1676-4aaf-83c4-6cf332bb5d7b.png)

**Comment by methane** [comment]
pymalloc aligns memory blocks with 2words (8byte on 32bit, 16byte on 64bit platform).

Currently, GC header is 2 words so no gap. If we add `__dict__` there, we need to add a gap.

**Comment by markshannon** [comment]
If we were to reduce the GC header to a single word, then placing the dict pointer before the header would be even more compelling as it would fill the gap.

**Comment by markshannon** [comment]
Given that allocations are two-word aligned, the pre-header needs to be an even number of words.

Long term we want this layout:

![popo_compact](https://user-images.githubusercontent.com/9448417/134365145-c5fcc872-667d-41d7-91ae-5b17273accbe.png)

But in the medium term, this gives us fixed offsets for dict and weakref pointers and is as compact as what we have now:

![popo_with_weakrefs](https://user-images.githubusercontent.com/9448417/134364944-cc6a2b96-6e8d-46e1-a6ac-3981710da68f.png)

**Comment by pxeger** [comment]
Maybe a noobish and/or off-topic question because I don't know much about CPython memory layout, but why is there anything *before* what the object pointer points to at all? Why not just keep it all before that?

**Comment by markshannon** [comment]
It needs to be at a fixed offset *and* allow for variable sized objects and inheritance.

**Comment by gvanrossum** [comment]
In particular, for ABI compatibility we need to keep ob_refcnt and ob_type at the same offset relative to the pointer.

**Comment by markshannon** [comment]
An alternative to the above, which will work well with https://github.com/faster-cpython/ideas/issues/72#issuecomment-924568858 is:
![popo_with_values](https://user-images.githubusercontent.com/9448417/135499702-a2494f2e-3d0b-4f2c-a2dd-26f1cebfcf53.png)

**Comment by markshannon** [comment]
"Custom" can contain anything. Fully backwards compatible and opaque to the GC.
Tuples would be "custom". Having custom layouts for things like tuples, lists and dicts is fine. They're special.

Code that sets `tp_dictoffset` is fine, that just means we have a custom layout.

Code that uses `tp_dictoffset` is problematic only in the case where we have the `__dict__` pointer in the header, *and* the class has instances of differing size, e.g. a tuple.

Which means that we can't use regular object layout for classes that inherit from `tuple`, `bytes`, etc.
I don't think that will be a problem in practice.

For example, this class:
```Python
class XTuple(tuple):
    pass
```
would not be able to have the `__dict__` pointer in the header, it would have to go in the "custom" section.

**Comment by markshannon** [comment]
I think this is done. We might want to tweak this later, but that can be its own issue.
FTR, the final layout chosen was https://github.com/faster-cpython/ideas/issues/80#issuecomment-931504847
