### ISSUE TITLE
Faster startup -- Experiment E -- "deep-freeze" code objects as static C data structures

### ISSUE THREAD

**Issue by gvanrossum** [faster-cpython/ideas#84]
~This idea was @markshannon's,~ _This a variant of something first proposed by Jeethu Rao of Facebook in https://bugs.python.org/issue34690._ I'm just writing it up (and I may try to execute). The name "deep-freeze" is Mark's.

We could write a Python script that generates C code for a code object (including nested code objects). This would completely avoid the need for unmarshalling frozen modules (but only those). It would replace the current approach to freezing the marshalled code objects (which also generates C code, but it's just an array of bytes).

Suppose a simple code object has 4 bytes of data, `"ABCD"`. We can then generate something like this:

```
static PyBytesObject co_code_1 = {
    .ob_refcnt = 999999999,
    .ob_type = &PyBytes_Type,
    .ob_size = 4,
    .ob_shash = -1,  // To be filled in dynamically
    .ob_sval = "ABCD"
};

static PyCodeObject code_1 = {
    ...
    co_code = &co_code_1,
    ...
};
```
(Lots of details left out, including the restructuring of object headers.)

An immediate concern here is the intended separation of static objects for multiple interpreters (@ericsnowcurrently). We're introducing something here that would be tricky to clone per interpreter. So maybe that kills the idea immediately?

Another concern is the initializer for `ob_sval` -- this field is actually declared as an array of 1 char, and the compiler will presumably balk if we put more in there. I think there's a solution though by declaring such bytes objects as a struct containing a modified header (omitting `ob_sval`) and a separate array of characters:
```
static struct {
    PyBytesObjectWithoutObSval head;  // PyBytesObject without ob_sval field
    char ob_sval[4+1];
} co_code_1 = {
    .head = {
        .ob_refcnt = 999999999,
        .ob_type = &PyBytes_Type,
        .ob_size = 4,
        .ob_shash = -1,
    },
    .ob_sval = "ABCD"
};
```

**Comment by ericsnowcurrently** [comment]
> An immediate concern here is the intended separation of static objects for multiple interpreters (@ericsnowcurrently). We're introducing something here that would be tricky to clone per interpreter. So maybe that kills the idea immediately?

Any `PyObject *` is not safely shareable in a world where interpreters no longer share a GIL.  So using those code objects as-is wouldn't work.  However, I wouldn't say it's a non-starter.  Here are some options (off the top of my head):

* `memcpy()` once for each interpreter (perhaps use the generated one as-is in the main interpreter)
* use structs that map to `PyCodeObject`, etc., instead of generating the various `PyObject` directly
   * creating the `PyCodeObject` from it is still much lighter than unmarshalling
   * the whole object graph could be allocated with a single `malloc()` (using computed offsets for each needed object)
* use a (semi) proxy type that wraps the generated `PyCodeObject`

**Comment by gvanrossum** [comment]
Brief status update:

- I can generate static data for 'hello world'
- It compiles
- It links, with a small dummy extension module that exports the code object
- It segfaults when I try to run the code object (`import hello; exec(hello.get_toplevel())`)

I got it to work on Windows and Mac, but the C compilers are a bit different. In the end on Windows (for MSVC) I had to pretend the generated code was C++ to get the initializers to compile. Also, MSVC insists that the fields in a code object are initialized in the order in which they are declared. It seems clang is not so picky. (This is a pain because the fields have been reordered for improved performance.)

Definitely still missing:

- More object types, in particular int, float, complex, frozenset
- Fill in several more fields of code objects (e.g. co_localsplus, which I have to reconstruct from co_varnames and friends); I suspect herein lies the cause of the segfault
- Hook it up with the frozen import infrastructure

I think we may still need the old frozen import infrastructure; that generates C code for frozen files from a C program, but the new code generator is too complex to write in C. That means we need a complete working Python interpreter to run the generator. And it must be the Python we're targeting, it can't be an older version, because it compiles the source and introspects the resulting code object as the input for the code generator.

**Comment by gvanrossum** [comment]
Another status report. I think I've got all fields of the code object filled in now -- a simple test program using cells seems to work.

Still to do:

- [ ] float
- [ ] complex
- [ ] frozenset
- [ ] **Integrate with freeze infrastructure**
- [ ] Perf measurements
- [ ] Integrate with Eric's "freeze 80 modules"

**Comment by dpgeorge** [comment]
In case you are interested, and maybe it leads to some inspiration: in MicroPython there is the concept of "frozen" code which is generated through the process: source -> compiled bytecode -> C data structure (.py -> .mpy -> .c).  The final C data structures contain compiled Python functions, all their nested functions/classes, and all their nested constant objects (str, bytes, long int, float).  They are all `const` so can be placed in ROM and don't need any fixup at load/import time.

The tool that converts .mpy (similar to .pyc) to .c is https://github.com/micropython/micropython/blob/master/tools/mpy-tool.py .  An example generated .c file is:
[frozen_content.c.txt](https://github.com/faster-cpython/ideas/files/7018227/frozen_content.c.txt) (that's pretty small, usually they are 10k+ lines, even up to 100k+).  Freezing code like this is the main way that MicroPython is used in production.

**Comment by gvanrossum** [comment]
Oh, that's very similar -- to the point where I'm glad MicroPython is also open source else we'd have to license the patent off you. :-) The main differences are:

- I'm using the compile() builtin instead of reading the compiled bytecode from a file
- CPython objects have in-line reference counts so the data can't be const or ROM-able

Also I expect that eventually we'll need some fixup, to support multiple interpreters (see discussion above). And eventually to handle frozenset.

**Comment by markshannon** [comment]
I think we could find some prior art :slightly_smiling_face:

One thing I found worked well doing this for HotPy, was using standardized names. That way if you reference the string "hello", you don't need to record when it went, just that it has been/will be emitted.
Reference to string "hello": `&str_hello`.
Reference to the tuple `("hi", 1)`: `&tuple2__str_hi__int_1` (make sure to escape underscores in strings).
etc, etc.

It also makes duplicates and missing references really easy to debug.

**Comment by brandtbucher** [comment]
> For now, I hacked around frozenset by generating a tuple. This works for "if x in {2, 3, 5}" and that's the only context where a frozenset can occur in a code object, AFAICT (it's put there by the AST optimizer).

There's one more place that I know of: constant set displays longer than two elements. It's done in the compiler, in `starunpack_helper`:

```py
>>> import dis
>>> dis.dis("{0, 1, 2}")
  1           0 BUILD_SET                0
              2 LOAD_CONST               0 (frozenset({0, 1, 2}))
              4 SET_UPDATE               1
              6 RETURN_VALUE

```

...though tuples probably work fine there as well.

**Comment by gvanrossum** [comment]
> One thing I found worked well doing this for HotPy, was using standardized names. That way if you reference the string "hello", you don't need to record where it went, just that it has been/will be emitted.
> Reference to string "hello": `&str_hello`.
> Reference to the tuple `("hi", 1)`: `&tuple2__str_hi__int_1` (make sure to escape underscores in strings).
> etc, etc.

I was thinking of using a similar mechanism as used by the bytecode compiler and by marshal to merge duplicates -- just keep a dict whose keys are `(type, value)` and whose values are (in this case) the name of the data structure generated for that value. Since everything is a DAG we just can generate things bottom up.

It may be nice though to have some indication of the value in the variable name -- currently the variable name just reflects where it is in the structure (e.g. `toplevel_consts_44_consts_3`).

In any case that's all just niceties. I've hooked everything up on UNIX (*) and it seems to work, although I haven't shown anything is faster yet. (Since I only have importlib/_bootstrap and importlib/_bootstrap_external working, based on Eric's flamegraph I'd expect only a 3-5% improvement, which is hard to measure on my Mac.)

A new concern is popping up in my head regarding bootstrapping: the code generator relies on the *built* Python interpreter -- it doesn't work with an older version, since the various fields of code objects have different meanings. But now suppose someone is changing the code object (for example, changing some bytecode instruction). We need to be able to run the generator without depending on the code it generated previously. The best thing I can think of for now is to have an environment variable that means "don't use generated code objects". Instead, it will fall back on the old frozen marshal data.

__________
(*) I don't want to create the MSVC project files until I have to, plus I doubt that we can link with C++ files.

**Comment by gvanrossum** [comment]
Quick note (also @ericsnowcurrently) :On Windows, since everything's linked statically into the core Python DLL, it suffices to add all the .c files to `PCbuild\pythobcore.vcxproj`. There's a long list of `<ClCompile .../>` items to which we can add these.

**Comment by gvanrossum** [comment]
Another quick note: According to Steve Dower, this was proposed a few years ago by Instagram and at a core sprint Larry made an implementation that saw 20-30% improvement (in startup time, I presume). Alas, the PR was rejected because people wanted to be able to edit the .py files and get those changes immediately effective. Apparently Larry solved this by also searching for the module on sys.path, but that brought the performance down to a meager 1% (not surprising because stat() is almost as expensive as open(), and read() is virtually free in comparison).

So we may have to deal with this somehow. For changes to the bytecode interpreter we can bake the magic number into the generated code and check it upon use (falling back on the disk version if there's no match), but for changes to the .py files users would at least have to remember to type "make". Hm.

**Comment by gvanrossum** [comment]
I have things kind of working with a variant on Eric's freeze 80 modules, but on my noisy Mac laptop I can't see much of a difference yet; the total time for "python -S -c pass" is ~16 ms each way, and the noise is 2-3 ms. :-(

The binary size tripled from 4.5 Mib to 13.4 Mib though, so I have to work on that (reducing that will also improve times).

**Comment by markshannon** [comment]
As various people seem keen to claim that that this was their idea. I would point out that  freezing the state of an executable is *much* older than any of the above claims, dating back to the 1980s at least.

As for applying it to Python, the original HotPy was built with freezing back in 2009, but the RPython tool chain could be considered an elaborate version of this idea and predates that by a few years.

**Comment by gvanrossum** [comment]
(Status update: I'm waiting for Eric Snow to finish several changes to the frozen modules infrastructure. Once that has landed and is deemed stable I will re-integrate my code with that infrastructure and do proper benchmarks to determine whether to proceed.

**Comment by gvanrossum** [comment]
Working on Windows now. This requires:

- [ ] Manually generate deep-frozen .c files
- [ ] Add lines like `<ClCompile Include="..\Python\deepfreeze\os.c" />` to `pythoncore.vcxproj`
- [ ] Figure out what to do about codecs.c (there's already `Python\codecs.c`)
- [ ] Update `deepfreeze.py` to run with any old Python (it must read the `.h` file written by `_freeze_module.exe` and then use a pure-Python `marshal.loads()` implementation)
- [ ] Update _freeze_module.vcxproj` to run the deepfreeze.py script (the `<Exec>` element is an implicit loop over whatever's given as `$(None.ModName)` etc.)

We can then also update the UNIX `Makefile` to get rid of `_bootstrap_python` (but there will still be dependencies).

**Comment by gvanrossum** [comment]
Despite the open items I consider this done.
