### ISSUE TITLE
Merge co_names and co_consts into a single array.

### ISSUE THREAD

**Issue by markshannon** [faster-cpython/ideas#92]
Merging `co_names` and `co_consts` would have some significant benefits:

1. It would make code objects smaller. There is unlikely to be much sharing between names and constants, but saving two tuples per code object is significant.
2. It would free up a register in the interpreter which should be worth a few percent speed up (in the interpreter, less overall).
3. By using an array, not a tuple, some lazy initialization of constants becomes possible. For example, a deep-frozen module might not be able to include frozen sets due to hashing; tuples could be stored and converted to frozen-sets on code object initialization.

The obvious downside is for functions where the total number of names and constants exceeds 256. I hypothesize that those functions are rare, but don't have data to confirm that.

This is probably best left until https://bugs.python.org/issue36521 has been resolved.

**Comment by pxeger** [comment]
I'm not sure what you mean by "But how often are they >= 255 *together*?".

The 0.12% number is already the proportion for which `len(co_consts) + len(co_names) >= 256`, not just the sum of the proportions for names and consts separately, if that's what you meant

**Comment by markshannon** [comment]
> Are there no backwards compatibility issues? They are both part of the api.
> 
> Also, would this make the consts not immutable from user code? That would probably be an api change.

The array would be internal, so could not be mutated. `co_consts` and `co_names` would be lazily created if needed.
