### ISSUE TITLE
Align quickened code to cache line boundaries

### ISSUE THREAD

**Issue by brandtbucher** [faster-cpython/ideas#95]
Statistically, ~40% of all allocations occupy one more cache line than they need to (assuming 64-byte cache lines and 8/16-byte `PyMalloc` alignment).

We’ve already determined that quickened code strings are hot, and unlike “normal” code strings (which are wrapped in a `bytes` object), we can more easily control the alignment of the memory that we use.

The idea is this: when quickening, we can overallocate memory for the quickened code by 64 bytes (actually, due to PyMalloc’s alignment rules, we can probably get away with 48 bytes on 64-bit platforms and 56 bytes on 32-bit platforms). This allows us to manually align the combined cache entires and quickened code to the nearest cache line after the fact by inserting “dummy” cache entries into the front of the array.

With this, we can guarantee that quickened code never occupies more cache lines than it needs to (meaning fewer evictions of hot instructions / cache entries and more effective hardware prefetching). The overhead, of course, is a constant 48-56 bytes of padding per quickened code string... though we could set some minimum size threshold for this optimization to be activated.

Thoughts?

**Comment by gvanrossum** [comment]
So the layout (see pycore_code.h) is
```
<cache_entry> <cache_entry> ... <cache_entry> | <instr> <instr> ... <instr>
```
with `co_firstinstr` pointing to the first `<instr>` and `co_quickened` pointing to the start of the array (also the first `<cache_entry>`, but they're only ever indexed by counting backwards from `co_firstinstr`). Your proposal is just to insert extra `<cache_entry>` items so that the first `<instr>` is aligned on a cache line, right? A cache entry is just 8 bytes, an instruction just 2. Given that everything's indexed from the middle, I don't understand how aligning that middle helps. So probably I'm missing something, or misunderstanding the scheme you propose?

**Comment by brandtbucher** [comment]
Sorry, I could have been clearer. My proposal is to align the *first real cache entry* on the cache line boundary:

```
<dummy> <dummy> ... <dummy> | <cache_entry> <cache_entry> ... <cache_entry> | <instr> <instr> ... <instr>
                            ^ cache line boundary                           ^ co_firstinstr
```

This way, all of the important data is packed together in as few cache lines as possible.

**Comment by brandtbucher** [comment]
Indeed, the results are "1.00x faster", which I'm guessing isn't worth the added complexity.

| Benchmark               | main    | align-quickened       |
|-------------------------|:-------:|:---------------------:|
| regex_v8                | 25.5 ms | 23.3 ms: 1.09x faster |
| unpack_sequence         | 46.0 ns | 43.4 ns: 1.06x faster |
| regex_effbot            | 3.31 ms | 3.14 ms: 1.06x faster |
| regex_dna               | 223 ms  | 215 ms: 1.03x faster  |
| unpickle                | 13.8 us | 13.4 us: 1.03x faster |
| float                   | 86.9 ms | 85.0 ms: 1.02x faster |
| telco                   | 6.42 ms | 6.31 ms: 1.02x faster |
| json_dumps              | 12.8 ms | 12.6 ms: 1.02x faster |
| chaos                   | 83.8 ms | 82.6 ms: 1.02x faster |
| spectral_norm           | 119 ms  | 117 ms: 1.01x faster  |
| xml_etree_parse         | 156 ms  | 154 ms: 1.01x faster  |
| pickle                  | 10.2 us | 10.0 us: 1.01x faster |
| mako                    | 12.7 ms | 12.6 ms: 1.01x faster |
| scimark_lu              | 149 ms  | 147 ms: 1.01x faster  |
| xml_etree_iterparse     | 107 ms  | 106 ms: 1.01x faster  |
| richards                | 59.5 ms | 59.0 ms: 1.01x faster |
| xml_etree_generate      | 84.7 ms | 84.1 ms: 1.01x faster |
| 2to3                    | 294 ms  | 293 ms: 1.01x faster  |
| crypto_pyaes            | 90.8 ms | 90.5 ms: 1.00x faster |
| meteor_contest          | 107 ms  | 107 ms: 1.00x faster  |
| pidigits                | 188 ms  | 188 ms: 1.00x faster  |
| sympy_integrate         | 22.2 ms | 22.3 ms: 1.00x slower |
| regex_compile           | 150 ms  | 151 ms: 1.00x slower  |
| hexiom                  | 7.78 ms | 7.81 ms: 1.00x slower |
| sqlalchemy_imperative   | 18.6 ms | 18.7 ms: 1.00x slower |
| xml_etree_process       | 61.2 ms | 61.5 ms: 1.01x slower |
| chameleon               | 7.56 ms | 7.61 ms: 1.01x slower |
| pickle_dict             | 29.5 us | 29.6 us: 1.01x slower |
| deltablue               | 5.29 ms | 5.32 ms: 1.01x slower |
| sympy_expand            | 512 ms  | 515 ms: 1.01x slower  |
| scimark_sor             | 159 ms  | 161 ms: 1.01x slower  |
| dulwich_log             | 68.9 ms | 69.4 ms: 1.01x slower |
| pyflate                 | 541 ms  | 546 ms: 1.01x slower  |
| nbody                   | 123 ms  | 124 ms: 1.01x slower  |
| sqlite_synth            | 2.74 us | 2.77 us: 1.01x slower |
| pickle_list             | 4.64 us | 4.71 us: 1.02x slower |
| logging_simple          | 6.72 us | 6.83 us: 1.02x slower |
| unpickle_list           | 4.78 us | 4.87 us: 1.02x slower |
| pathlib                 | 19.2 ms | 19.6 ms: 1.02x slower |
| go                      | 175 ms  | 179 ms: 1.02x slower  |
| logging_format          | 7.32 us | 7.50 us: 1.03x slower |
| scimark_sparse_mat_mult | 4.95 ms | 5.08 ms: 1.03x slower |
| fannkuch                | 425 ms  | 438 ms: 1.03x slower  |
| logging_silent          | 124 ns  | 129 ns: 1.04x slower  |
| Geometric mean          | (ref)   | 1.00x faster          |

**Comment by brandtbucher** [comment]
Yep, it's super convenient. Eric walked me through the workflow with that machine today (and that's how I ran these).
