### ISSUE TITLE
Consider what programs to run during PGO

### ISSUE THREAD

**Issue by ammaraskar** [faster-cpython/ideas#99]
In the discussions of when PGO was added to the `Makefile`, there were some questions of whether the set of unit tests we run are representative of a real load. I wonder if anyone has tried using PGO with more "realistic" programs or a different set of tests and what impact that would have on performance.

**Comment by brandtbucher** [comment]
> We (the Pyston team) tried experimenting with this and we ran into the issue that it's not currently possible to install packages at PGO-task time. I don't think it's theoretically impossible though, but it did limit the tasks we could run.

Just curious: what's the issue with this? It seems like the instrumented Python should still be capable of building a virtual environment with `venv`, installing packages, and running some workload as part of a profile task?

Sure, that work would ultimately "count towards" the profile data, but it's probably still a more realistic workload than the tests we're running now. And it would probably be tiny in comparison to the actual profile task.

**Comment by ericsnowcurrently** [comment]
Ideally:

1. identify a set of fundamental workloads representing use in the Python community
2. ensure there is at least one high-level, not-too-fast benchmark representing each
3. use that suite for a daily "slow" run, as well as to train PGO

By "not-too-fast" I'm talking about how long the benchmark takes to run.  Pretty much every one of the current pyperformance benchmarks runs in a fraction of a second.  In contrast, we want the real-world benchmarks to represent actual workload behavior as closely as possible, including duration (within reason).  So some quick scripts will run in under a second but some apps may run for several minutes.

Thus this new suite wouldn't be suitable for the quick benchmark runs that we do throughout the day.  Instead we'd probably run it once a day (which happens to match the frequency of uploads to speed.python.org 🙂).  It just so happens that it would also be great for training PGO.
